### ISSUE TITLE
fix cassandra sink test

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#17855] opened 2024-07-30 03:24 UTC
@kwannoel: The installation step for the cassandra binary is failing for over a week. So the entire cassandra test is not running anyway. I will disable it first.

The solution is to always pull the latest binaries.

**Comment by hzxa21** [comment] 2024-10-08 09:01
@xxhZs Can you confirm that the issue is fixed by #17493? You can close the issue if yes.

**Closed** 2024-10-08 09:22 UTC
Labels: type/feature, no-issue-activity
