### ISSUE TITLE
chaos-mesh `podchaos` failure: `actor 64 not found in info table`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#19536] opened 2024-11-22 04:43 UTC
### Describe the bug

https://buildkite.com/risingwave-test/chaos-mesh/builds/1166#01934f59-c721-4cf0-8600-52124c801f6d

### Error message/log

```text
Opening a connection
Running command show create materialized view nexmark_q0_1;
Opening a connection
Running command CREATE MATERIALIZED VIEW nexmark_q0_1_chaos_mesh AS SELECT auction, bidder, price, date_time FROM bid
Failed to run the query
Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: get error from control stream, in worker node 6
  3: gRPC request to stream service failed: Internal error
  4: failed to handle barrier event
  5: Actor 1136 exited unexpectedly
  6: actor 64 not found in info table
```
```


### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

https://buildkite.com/risingwave-test/chaos-mesh/builds?branch=main

The first time appeared on Nov 13th

And repeatedly triggered in recent executions

**Comment by lmatz** [comment] 2024-11-22 04:47
![SCR-20241122-hqg](https://github.com/user-attachments/assets/6d9f3842-c56e-445d-9db2-76b11a785d05)

**Comment by wenym1** [comment] 2024-12-25 03:14
Chaos mech test has been successful since https://github.com/risingwavelabs/risingwave/pull/19579 is merged.

**Closed by wenym1** 2024-12-25 03:14 UTC
Labels: type/bug, found-by-chaos-mesh

**Comment by wenym1** [comment] 2024-12-26 07:42
Found a way to reproduce the bug locally thanks to @shanicky 

Launch a cluster and create a table
```
./risedev d ci-3cn-1fe-with-recovery

create table t(v int);
```

Run the following command to add a new worker node
```
.risingwave/bin/risingwave/compute-node --config-path .risingwave/config/risingwave.toml --listen-addr 127.0.0.1:5686 --prometheus-listener-addr 127.0.0.1:1225 --advertise-addr 127.0.0.1:5686 --async-stack-trace verbose --parallelism 6 --total-memory-bytes 8589934592 --role both --meta-address http://127.0.0.1:5690 --data-file-cache-dir .risingwave/data/foyer/5686/data --meta-file-cache-dir .risingwave/data/foyer/5686/meta
```

In some cases, the bug can be reproduced by now when triggering the auto scale. If the bug unluckily does not happen, we can further run `create materialized view mv as select * from t;`, and the bug must be able to reproduced.

Root cause is described in https://github.com/risingwavelabs/risingwave/pull/19939.
