### ISSUE TITLE
bug: "Failed to fetch filter key extractor tables" causing compaction task to fail until restarting meta node

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#14459] opened 2024-01-09 14:08 UTC
### Describe the bug

We see these message flooding the compactor log and compaction tasks keeps failing until meta node restart
"Failed to fetch filter key extractor tables [{35157}. [[35157]] may be removed by meta-service. "
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/442161ce-f75c-4870-92cc-7ec98155dc6a)

### The version of RisingWave

1.5.1

**Comment by zwang28** [comment] 2024-01-09 14:10
It happened once before. I suspect there is a code path that a failed/cancelled stream job doesn't [notify hummock manager](https://github.com/risingwavelabs/risingwave/blob/be30f20e2c14b5d12efd5b33a4ac9e537602fc37/src/meta/src/hummock/manager/compaction_group_manager.rs#L265).

**Comment by zwang28** [comment] 2024-03-07 03:08
duplicate of #15144

**Closed by zwang28** 2024-03-07 03:08 UTC
Labels: type/bug

**Comment by zwang28** [comment] 2024-03-07 03:12
> May be related: https://github.com/risingwavelabs/risingwave/pull/15355. Do we know whether this issue can occur without https://github.com/risingwavelabs/risingwave/pull/15355? cc @zwang28

There have been quite some changes between v1.5.1 when this issue occurred, and latest v1.7.
I'll look into it in v1.7.
