### ISSUE TITLE
sqlsmith enconters internal error: transport error

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#11073] opened 2023-07-19 12:16 UTC
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/27642#01896d48-a57b-490b-95ca-ab9ae79270d4

### Error message/log

```text
[TEST STREAM]: CREATE MATERIALIZED VIEW stream_query AS SELECT t_0.col_0 AS col_0, last_value(DISTINCT t_1.col_0 ORDER BY t_1.col_0 DESC NULLS LAST, t_1.col_0 ASC NULLS LAST, t_1.col_0 DESC) AS col_1, t_0.col_0 AS col_2 FROM m12 AS t_0 FULL JOIN m12 AS t_1 ON t_0.col_0 = t_1.col_0 AND true GROUP BY t_0.col_0

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Encountered unexpected error: db error: ERROR: QueryError: internal error: transport error
```

**Comment by kwannoel** [comment] 2023-07-19 14:51
Seems like a newly introduced error. Did not see it before. Will try to find the regression.

**Comment by fuyufjh** [comment] 2023-08-08 09:16
Any updates?

**Comment by kwannoel** [comment] 2023-09-07 02:44
> Any updates?

Duplicate of https://github.com/risingwavelabs/risingwave/issues/12140.

The underlying reason is memtable inconsistent, and somehow cluster does not exit immediately but hangs.

**Closed** 2023-09-07 02:44 UTC
Labels: type/bug
