### ISSUE TITLE
DBeaver created table not showing

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#12056] opened 2023-09-04 08:35 UTC
### Describe the bug

When I am creating a table using DBeaver I am unable to see this table after creation. Using my local dev environment, started with `risedev p`.
```
git log -1
commit 2ea66b8dce1af72e22540f450d20b277753414d2 (HEAD -> main, origin/main, origin/HEAD)
Author: Bohan Zhang <tabvision@bupt.icu>
Date:   Mon Sep 4 16:15:30 2023 +0800

    chore: refine error message on unhandled error in kinesis (#12055)
```
CC @neverchanje I believe you worked on the DBeaver integration?

<img width="1219" alt="Screenshot 2023-09-04 at 10 21 32" src="https://github.com/risingwavelabs/risingwave/assets/15103784/06b5a169-66d7-4826-8dbb-f52a2b1fa0c2">
<img width="1219" alt="Screenshot 2023-09-04 at 10 20 54" src="https://github.com/risingwavelabs/risingwave/assets/15103784/b859e1e1-6428-415b-931a-427f937ee7a8">

**Comment by TennyZhuang** [comment] 2023-12-05 04:54
I can't reproduce it in recent version, close it now.

**Closed by TennyZhuang** 2023-12-05 04:54 UTC
Labels: type/bug
