### ISSUE TITLE
v2.0.0-rt.4 chaos mesh PG CDC ch-benchmark q10 inconsistency

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#18504] opened 2024-09-12 06:09 UTC
### Describe the bug

https://buildkite.com/risingwave-test/chaos-mesh/builds/1039#0191e434-823d-47b4-a650-d412af06156d

```
{
--
  | "url": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
  | "database-name": "postgres",
  | "database-checksum": 2618155919451936995,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
  | "table-name": "ch_benchmark_q10",
  | "table-checksum": 2618155919451936995,
  | "table-rows": 28873
  | }
  | ]
  | }
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "database-name": "dev",
  | "database-checksum": 831684243593628827,
  | "table-checksums": [
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "ch_benchmark_q10",
  | "table-checksum": 831684243593628827,
  | "table-rows": 28873
  | }
  | ]
  | }
  | {
  | "consistent": false,
  | "table-compare-results": [
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "warehouse",
  | "table-checksum": -2456723423649949855,
  | "table-rows": 1
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "warehouse",
  | "table-checksum": -4992093762855733666,
  | "table-rows": 1
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "district",
  | "table-checksum": 3651224502201311617,
  | "table-rows": 10
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "district",
  | "table-checksum": -285716814300879220,
  | "table-rows": 10
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "customer",
  | "table-checksum": -2486302212674361214,
  | "table-rows": 30000
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "customer",
  | "table-checksum": -1806650838040018610,
  | "table-rows": 30000
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "history",
  | "table-checksum": 1937209160774715871,
  | "table-rows": 45000
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "history",
  | "table-checksum": 2598855456682300627,
  | "table-rows": 45000
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "new_order",
  | "table-checksum": -7018323244907310301,
  | "table-rows": 8
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "new_order",
  | "table-checksum": -1238522194174823813,
  | "table-rows": 8
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "orders",
  | "table-checksum": 7480572064488528834,
  | "table-rows": 110404
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "orders",
  | "table-checksum": -7407215619529639533,
  | "table-rows": 110404
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "order_line",
  | "table-checksum": -5701103227921376824,
  | "table-rows": 1103571
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "order_line",
  | "table-checksum": -3736173396463305925,
  | "table-rows": 1098569
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "stock",
  | "table-checksum": -7106905234210571750,
  | "table-rows": 100000
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "stock",
  | "table-checksum": -4432975427228685253,
  | "table-rows": 100000
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "item",
  | "table-checksum": -541044434550332794,
  | "table-rows": 100000
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "item",
  | "table-checksum": 6203962560316800121,
  | "table-rows": 100000
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "nation",
  | "table-checksum": 4140424216966173119,
  | "table-rows": 25
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "nation",
  | "table-checksum": -3810634810117666287,
  | "table-rows": 25
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "region",
  | "table-checksum": 5923708037939308992,
  | "table-rows": 5
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "region",
  | "table-checksum": 6296436568714307961,
  | "table-rows": 5
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "supplier",
  | "table-checksum": -1496706393295477220,
  | "table-rows": 10000
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "supplier",
  | "table-checksum": 1227956253642296328,
  | "table-rows": 10000
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "revenue1",
  | "table-checksum": 2449304151315185796,
  | "table-rows": 10000
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "revenue1",
  | "table-checksum": 3811769880545160651,
  | "table-rows": 10000
  | }
  | ]
  | },
  | {
  | "consistent": false,
  | "table-checksums": [
  | {
  | "url": "postgres://postgres:postgres@localhost:5432/postgres",
  | "table-name": "ch_benchmark_q10",
  | "table-checksum": 2618155919451936995,
  | "table-rows": 28873
  | },
  | {
  | "url": "postgres://root:@127.0.0.1:4567/dev",
  | "table-name": "ch_benchmark_q10",
  | "table-checksum": 831684243593628827,
  | "table-rows": 28873
  | }
  | ]
  | }
  | ]
  | }
  | warehouse table/mv data checksum inconsistent
  | district table/mv data checksum inconsistent
  | customer table/mv data checksum inconsistent
  | history table/mv data checksum inconsistent
  | new_order table/mv data checksum inconsistent
  | orders table/mv data checksum inconsistent
  | order_line table/mv data checksum inconsistent
  | stock table/mv data checksum inconsistent
  | item table/mv data checksum inconsistent
  | nation table/mv data checksum inconsistent
  | region table/mv data checksum inconsistent
  | supplier table/mv data checksum inconsistent
  | revenue1 table/mv data checksum inconsistent
  | ch_benchmark_q10 table/mv data checksum inconsistent
```

### The version of RisingWave

v2.0.0-rt.4

**Comment by lmatz** [comment] 2024-09-12 10:46
I think we need to tag going forward for better visibility, WDYT? @cyliu0

**Comment by StrikeW** [comment] 2024-09-17 12:16
This issue should be temporary, cannot reproduce with rerun. I think we can close this issue.

**Closed** 2024-09-17 12:17 UTC
Labels: type/bug
