### ISSUE TITLE
perf: sysbench throughput is much lower than expection

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7165] opened 2023-01-03 08:28 UTC
> The performance of sysbench is much lower than our manual test… For example, the throughput of point-select is ~800 QPS while in https://singularity-data.quip.com/9racAbR17zmC/SysBench-For-RisingWave it was ~70K. This seems to be far beyond the impact due to different hardware configurations

Previously discussed in https://risingwave-labs.slack.com/archives/C04879XJ36C/p1672716819131519?thread_ts=1672711831.022119&cid=C04879XJ36C

**Comment by lmatz** [comment] 2023-01-03 09:02
The execution is deployed by https://github.com/risingwavelabs/kube-bench/tree/main/manifests/benchmarks/sysbench

**Comment by lmatz** [comment] 2023-01-03 09:07
```
[benchmark]
--
  | namespace = "sysbench-daily-test-20221230"
  |  
  | [benchmark.aws]
  | ask_before_proceed = false
  |  
  | [benchmark.job]
  | name = "benchmark-job"
  | type = "sysbench"
  |  
  | [benchmark.sysbench]
  | threads = "16"
  | report_interval = 1
  | events = 0
  | time = 10
  | percentile = 99
  | auto_inc = false
  | table_size = "10000000"
  | db_ps_mode = "disable"
  | skip_trx = true
  | range_size = 1
  | # Possible values are oltp_point_select.lua, select_random_points.lua, select_random_ranges.lua and oltp_read_only.lua
  | task = "oltp_point_select.lua"
  | image = { tag = "latest" }
  |  
  | [benchmark.risingwave]
  | version = "nightly-20221229"
  |  
  | [benchmark.risingwave.replicas]
  | meta = 1
  | frontend = 1
  | compute = "3"
  | compactor = 1
  |  
  | [benchmark.risingwave.resources]
  | cpu = { limit = "8", request = "8" }
  | mem = { limit = "16Gi", request = "16Gi" }
  |  
  | [benchmark.risingwave.storage]
  | type = "s3"
  |  
  | [benchmark.risingwave.storage.s3]
  | region = "ap-southeast-1"
  | access_key = ""
  | access_secret = ""
  | bucket = "sysbench-daily-test-20221230-2796"
  | data_directory = "hummock_001"
  |  
  | [benchmark.s3.bucket]
  | create_enabled = true
  | delete_enabled = true
  |  
  | [benchmark.kafka]
  | enabled = false
```
Buildkite URL: https://buildkite.com/risingwave-test/sysbench/builds/131#0185646d-30fe-44c1-a675-22bb61f978b1

**Comment by lmatz** [comment] 2023-01-03 09:08
In Dylan's report, 
the setting is `a single EC2 Machine (c5.12xlarge 48c96G) and run the SysBench program on another EC2 (c5.12xlarge 48c96G) in the same VPC.`

**Comment by liurenjie1024** [comment] 2023-01-03 09:22
After checking with @hzxa21 together, it's caused by two problems:

1. Due to the limitation of write throughtput, we are still processing writes when reading, so this is essentially read/write performance.
2. Block cache miss. We found that 63% of reads didn't hit block cache.

So, given the current data size, we should go with 2 changes:

1. Wait several minutes after inserts, or execute `SET RW_IMPLICIT_FLUSH TO true;` just like our e2e test.
2. Increase block cache size to 2G.

**Comment by fuyufjh** [comment] 2023-01-30 03:49
Still not stable. Leave it open.

**Comment by liurenjie1024** [comment] 2023-03-13 11:12
After using isolated environment, the performance is much stable now. Let's close it.

**Closed by liurenjie1024** 2023-03-13 11:12 UTC
Labels: component/batch, type/perf
