### ISSUE TITLE
bug: compactor: L0 SST count/size keeps growing when running NexMark Q7

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4927] opened 2022-08-26 11:27 UTC
### Describe the bug

Running NexMark Q7 for 4 hours and the L0 SST Count keeps growing.

<img width="1842" alt="image" src="https://user-images.githubusercontent.com/10192522/186893992-9bc131c9-02aa-4bbd-96b5-aa9e953d0d7e.png">

**Comment by hzxa21** [comment] 2022-08-26 11:36
Originally we suspected this is because we start compactor and CN in the same process, causing a single-threaded compaction runtime being used. But after checking the instance, the compactor node is a separated process started with:
```
/home/ubuntu/risingwave/.risingwave/bin/risingwave/compactor --config-path /home/ubuntu/risingwave/.risingwave/config/risingwave.toml --host 127.0.0.1:6660 --prometheus-listener-addr 127.0.0.1:1260 --client-address 127.0.0.1:6660 --metrics-level 1 --max-concurrent-task-number 15 --state-store hummock+minio://hummockadmin:hummockadmin@127.0.0.1:9301/hummock001 --meta-address http://127.0.0.1:5690/
```
max concurrent task number is set to 15 so it should take at most 15 tasks if the compaction scheduler has generated enough tasks.

Also, when the source stops, no new compaction tasks are generated.

**Comment by hzxa21** [comment] 2022-08-26 11:37
[compactor-6660.log](https://github.com/singularity-data/risingwave/files/9432793/compactor-6660.log)
[meta-node-5690.log](https://github.com/singularity-data/risingwave/files/9432794/meta-node-5690.log)


Confirmed that the compactor limit is not hit: didn't see `No idle compactor available.` in meta log

**Comment by hzxa21** [comment] 2022-08-26 11:38
cc @zwang28 @Little-Wallace @Li0k

**Comment by hzxa21** [comment] 2022-08-26 15:19
See [here ](https://risingwave-labs.slack.com/archives/C03U9AB2P45/p1661511712478209) for Investigation details.

Summary:
1. The cluster has been restarted before this benchmark runs.
2. Most of the files in L5 and L6 are marked as being compacted before the cluster restarts but never unmarked after the cluster is restarted. This is because the restarted compactor and meta node will neither resume or cancel the previously assigned task.
3. Due to 1) and 2), during this benchmark runs, only L0->L0 compaction can be triggered, which causes compaction lags.
4. Also, since all services (minio, meta, compactor, cn, frontend, ...) are deployed in a single node, CPU and I/O are under heavy load, which makes things wrose.

Action items:
- #4496 can resolve this issue since assigned task will be expired if no progress is reported from the compactor.
- We should also cancel all pending tasks of the compactor (if any) when a compactor joins the cluster because compaction task cannot survive across compactor process restarts.


Thanks @zwang28 @Little-Wallace @Li0k  for taking quick reactions and the joint effort of investigating this issue :)

**Comment by zwang28** [comment] 2022-09-06 06:00
Closed by https://github.com/risingwavelabs/risingwave/pull/4496

**Closed by zwang28** 2022-09-06 06:00 UTC
Labels: type/bug, component/storage
