### ISSUE TITLE
streaming: Top-N executor uses too much memory

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6091] opened 2022-10-28 06:56 UTC
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/25862682/198522929-0049f7eb-fc45-4f26-9523-37b2585e720e.png">

```sql
create source bid (auction INTEGER, bidder INTEGER, price INTEGER, "date_time" TIMESTAMP)
with (
  connector = 'nexmark',
  nexmark.table.type = 'Bid',
  nexmark.split.num = '3',
  nexmark.min.event.gap.in.ns = '0'
) row format json;

create materialized view mv as select * from bid order by price desc limit 100;
```

With `limit 100`, Top-N uses 5GB+ memory. Is this expected?

**Comment by fuyufjh** [comment] 2022-11-09 06:27
I think only the data of the top 100 * `TOPN_CACHE_HIGH_CAPACITY_FACTOR` = 200 elements should be kept in memory. Others should be evicted.

**Comment by BowenXiao1999** [comment] 2022-11-09 10:33
First I tried to reproduce locally. But seems can not:
I use `./risedev dev playground-3cn` and enable minio + Grafana. 
The memory is not that high as above, same for the throughput. What's your setup?
<img width="1853" alt="image" src="https://user-images.githubusercontent.com/36908971/200806788-d8eab923-a4e2-43c9-af44-b29fc3709888.png">
BTW, after about 30mins, seems like the meta crashed and the source throughput increase 400% and the memory also soaring up. Also confuse me.



Second I reviewed the code a lot. if `TIES` specified, then indeed the cache can become huge (exceed size limit), but this is not the case here. For now I can not explain the memory usage. Any clues? cc @xxchan @StrikeW

**Comment by BugenZhao** [comment] 2022-11-09 10:45
Could this be simply caused by write-back of the block cache? cc @hzxa21 😨

**Comment by hzxa21** [comment] 2022-11-10 02:32
> Could this be simply caused by write-back of the block cache? cc @hzxa21 😨

Do you still have the grafana data? Let's check the "Cache Size" panel in the Hummock section to see the block cache usage.

**Comment by fuyufjh** [comment] 2022-11-15 04:32
@BugenZhao Can you help to reproduce that memory usage?

> Second I reviewed the code a lot. if TIES specified, then indeed the cache can become huge (exceed size limit), but this is not the case here.

@BowenXiao1999 Do you mean when there are too many tied elements? Or just another bug?

**Comment by BowenXiao1999** [comment] 2022-11-15 04:38
> @BowenXiao1999 Do you mean when there are too many tied elements? Or just another bug?

Yes, seems like we do not have mechanism to prevent too many tied elements out there. Maybe a potential problem...

For example, in some while loop, insert into cache but do not break
https://github.com/risingwavelabs/risingwave/blob/f79bd9e7719cf5d712e6cfe7d2587db771205941/src/stream/src/executor/managed_state/top_n/top_n_state.rs#L177-L180

**Comment by xxchan** [comment] 2022-11-15 08:42
Yes, TopN with ties indeed can use unbounded memory (but doesn't seem to be the cause for the issue). We thought it's a rare extreme case and may resolve it in the future if necessary. 

BTW, other executors seem to have similar problems. e.g., if a hash join have extremely large number of rows with the same join key, it can use unbounded memory when loading them into cache.

**Comment by fuyufjh** [comment] 2022-11-15 08:51
+1, I think it's acceptable.

BTW, does TopN operator expose some metrics of cached rows? At least it can help us to identify the problem quickly in case.

**Comment by xxchan** [comment] 2022-11-15 08:54
> does TopN operator expose some metrics of cached rows?

Currently no. I will add some.

**Comment by fuyufjh** [comment] 2022-11-21 07:27
@BugenZhao Since this issue cannot be reproduced, I'll close it now. Feel free to reopen it if seen again.

**Closed by fuyufjh** 2022-11-21 07:27 UTC
Labels: type/enhancement, component/streaming, type/perf
