### ISSUE TITLE
perf: nexmark q14

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8503] opened 2023-03-13 07:56 UTC
Query:
```
CREATE MATERIALIZED VIEW nexmark_q14 AS
SELECT
  auction,
  bidder,
  0.908 * price as price,
  CASE
    WHEN
      extract(hour from date_time) >= 8 AND
      extract(hour from date_time) <= 18
    THEN 'dayTime'
    WHEN
      extract(hour from date_time) <= 6 OR
      extract(hour from date_time) >= 20
    THEN 'nightTime'
    ELSE 'otherTime'
  END AS bidTimeType,
  date_time
  -- extra
  -- TODO: count_char is an UDF, add it back when we support similar functionality.
  -- https://github.com/nexmark/nexmark/blob/master/nexmark-flink/src/main/java/com/github/nexmark/flink/udf/CountChar.java
  -- count_char(extra, 'c') AS c_counts
FROM bid
WHERE 0.908 * price > 1000000 AND 0.908 * price < 50000000;
```

RW:
```
 StreamMaterialize { columns: [auction, bidder, price, bidtimetype, date_time, _row_id(hidden)], pk_columns: [_row_id], pk_conflict: "no check" }
 └─StreamExchange { dist: HashShard(_row_id) }
   └─StreamProject { exprs: [Field(bid, 0:Int32) as $expr1, Field(bid, 1:Int32) as $expr2, (0.908:Decimal * Field(bid, 2:Int32)) as $expr3, Case(((Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 8:Int32) AND (Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 18:Int32)), 'dayTime':Varchar, ((Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 6:Int32) OR (Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 20:Int32)), 'nightTime':Varchar, 'otherTime':Varchar) as $expr4, Field(bid, 5:Int32) as $expr5, _row_id] }
     └─StreamFilter { predicate: ((0.908:Decimal * Field(bid, 2:Int32)) > 1000000:Int32) AND ((0.908:Decimal * Field(bid, 2:Int32)) < 50000000:Int32) AND (event_type = 2:Int32) }
       └─StreamRowIdGen { row_id_index: 4 }
         └─StreamSource { source: "nexmark", columns: ["event_type", "person", "auction", "bid", "_row_id"] }
```

Flink:
```
== Optimized Physical Plan ==
Calc(select=[bid.auction AS auction, bid.bidder AS bidder, *(0.908:DECIMAL(4, 3), bid.price) AS price, CASE(AND(>=(EXTRACT(FLAG(HOUR), CAST(dateTime AS TIMESTAMP(3))), 8), <=(EXTRACT(FLAG(HOUR), CAST(dateTime AS TIMESTAMP(3))), 18)), _UTF-16LE'dayTime':VARCHAR(9) CHARACTER SET "UTF-16LE", OR(<=(EXTRACT(FLAG(HOUR), CAST(dateTime AS TIMESTAMP(3))), 6), >=(EXTRACT(FLAG(HOUR), CAST(dateTime AS TIMESTAMP(3))), 20)), _UTF-16LE'nightTime':VARCHAR(9) CHARACTER SET "UTF-16LE", _UTF-16LE'otherTime':VARCHAR(9) CHARACTER SET "UTF-16LE") AS bidTimeType, dateTime, bid.extra AS extra], where=[AND(=(event_type, 2), >(*(0.908:DECIMAL(4, 3), bid.price), 1000000), <(*(0.908:DECIMAL(4, 3), bid.price), 50000000))])
+- WatermarkAssigner(rowtime=[dateTime], watermark=[-(dateTime, 4000:INTERVAL SECOND)])
   +- Calc(select=[event_type, bid, CASE(=(event_type, 0), person.dateTime, =(event_type, 1), auction.dateTime, bid.dateTime) AS dateTime])
      +- TableSourceScan(table=[[default_catalog, default_database, datagen]], fields=[event_type, person, auction, bid])

== Optimized Execution Plan ==
Calc(select=[bid.auction AS auction, bid.bidder AS bidder, (0.908 * bid.price) AS price, CASE(((EXTRACT(HOUR, CAST(dateTime AS TIMESTAMP(3))) >= 8) AND (EXTRACT(HOUR, CAST(dateTime AS TIMESTAMP(3))) <= 18)), 'dayTime', ((EXTRACT(HOUR, CAST(dateTime AS TIMESTAMP(3))) <= 6) OR (EXTRACT(HOUR, CAST(dateTime AS TIMESTAMP(3))) >= 20)), 'nightTime', 'otherTime') AS bidTimeType, dateTime, bid.extra AS extra], where=[((event_type = 2) AND ((0.908 * bid.price) > 1000000) AND ((0.908 * bid.price) < 50000000))])
+- WatermarkAssigner(rowtime=[dateTime], watermark=[(dateTime - 4000:INTERVAL SECOND)])
   +- Calc(select=[event_type, bid, CASE((event_type = 0), person.dateTime, (event_type = 1), auction.dateTime, bid.dateTime) AS dateTime])
      +- TableSourceScan(table=[[default_catalog, default_database, datagen]], fields=[event_type, person, auction, bid])
```

**Comment by fuyufjh** [comment] 2023-03-13 08:04
We are using blackhole sink for performance test, right?

I am not sure whether it is the bottle neck, but I guess Flink may not have this Exchange

```
└─StreamExchange { dist: HashShard(_row_id) }
```

which is tracked by #7377 cc. @shanicky

**Comment by lmatz** [comment] 2023-03-13 08:18
```
-----------------
 StreamSink { type: append-only, columns: [auction, bidder, price, bidtimetype, date_time] }
 └─StreamProject { exprs: [$expr1, $expr2, $expr3, $expr4, $expr5] }
   └─StreamProject { exprs: [Field(bid, 0:Int32) as $expr1, Field(bid, 1:Int32) as $expr2, (0.908:Decimal * Field(bid, 2:Int32)) as $expr3, Case(((Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 8:Int32) AND (Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 18:Int32)), 'dayTime':Varchar, ((Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 6:Int32) OR (Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 20:Int32)), 'nightTime':Varchar, 'otherTime':Varchar) as $expr4, Field(bid, 5:Int32) as $expr5, _row_id] }
     └─StreamFilter { predicate: ((0.908:Decimal * Field(bid, 2:Int32)) > 1000000:Int32) AND ((0.908:Decimal * Field(bid, 2:Int32)) < 50000000:Int32) AND (event_type = 2:Int32) }
       └─StreamRowIdGen { row_id_index: 4 }
         └─StreamSource { source: "nexmark", columns: ["event_type", "person", "auction", "bid", "_row_id"] }
(6 rows)
```

**Comment by BugenZhao** [comment] 2023-03-13 09:41
I guess this might be caused by a similar issue of https://github.com/risingwavelabs/risingwave/pull/5130. We need to evaluate a lot of `'HOUR'` constants for calling `EXTRACT`.

https://github.com/risingwavelabs/risingwave/blob/c907a563e9de9f8cddc53421d7b0948faa86ef15/src/expr/src/expr/expr_binary_nonnull.rs#L359-L401

**Comment by st1page** [comment] 2023-03-14 06:02
> RW Blackhole:
> 
> ```
> -----------------
>  StreamSink { type: append-only, columns: [auction, bidder, price, bidtimetype, date_time] }
>  └─StreamProject { exprs: [$expr1, $expr2, $expr3, $expr4, $expr5] }
>    └─StreamProject { exprs: [Field(bid, 0:Int32) as $expr1, Field(bid, 1:Int32) as $expr2, (0.908:Decimal * Field(bid, 2:Int32)) as $expr3, Case(((Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 8:Int32) AND (Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 18:Int32)), 'dayTime':Varchar, ((Extract('HOUR':Varchar, Field(bid, 5:Int32)) <= 6:Int32) OR (Extract('HOUR':Varchar, Field(bid, 5:Int32)) >= 20:Int32)), 'nightTime':Varchar, 'otherTime':Varchar) as $expr4, Field(bid, 5:Int32) as $expr5, _row_id] }
>      └─StreamFilter { predicate: ((0.908:Decimal * Field(bid, 2:Int32)) > 1000000:Int32) AND ((0.908:Decimal * Field(bid, 2:Int32)) < 50000000:Int32) AND (event_type = 2:Int32) }
>        └─StreamRowIdGen { row_id_index: 4 }
>          └─StreamSource { source: "nexmark", columns: ["event_type", "person", "auction", "bid", "_row_id"] }
> (6 rows)
> ```

I am not sure if the behavior here is proper. we have `source_partitions` and `parallelism`. But for the too-simple query which comprises of only 1 fragment. the parallelism will be the number of source partitions. if a user writes some heavy CPU computing with the project or filter executor. It might be better to shuffle the data into more shards with higher parallelism.

**Comment by BugenZhao** [comment] 2023-03-14 07:35
Occasionally I encounter segmentation faults or bad performance on Mac **only** for Nexmark Q14. Considering #6205, I'm extremely suspicious that it's caused by the backtrace capture here: when we try to extract the `HOUR`, we'll first try `extract_date` and then it returns an error.

https://github.com/risingwavelabs/risingwave/blob/8183b41565afcbd3ab3e2dd0b279b183973ceaca/src/expr/src/vector_op/extract.rs#L51-L58

**Comment by fuyufjh** [comment] 2023-03-15 04:19
The CPU ultilization looks good after #8538. Let's wait for next performance report.

(parallelism = 4)

<img width="364" alt="image" src="https://user-images.githubusercontent.com/10192522/225205353-e851c5bd-0cec-423a-a6b4-3856885394dc.png">

**Comment by lmatz** [comment] 2023-03-15 04:20
Running Q14 right now as the last night's performance test failed

**Comment by lmatz** [comment] 2023-03-15 16:36
![SCR-20230316-qn](https://user-images.githubusercontent.com/5791930/225377351-8920e3f5-7484-48d0-8d94-4f5f7b9798d7.png)

OK, now it's 893.8K 😆 

But as
> I guess this might be caused by a similar issue to https://github.com/risingwavelabs/risingwave/pull/5130. We need to evaluate a lot of 'HOUR' constants for calling EXTRACT.

we still keep this open?

**Comment by BugenZhao** [comment] 2023-03-15 16:39
> we still keep this open?

LGTM. I guess there won't be significant difference compared to the "backtrace" one 😄, but it's indeed a possible optimization.

**Comment by lmatz** [comment] 2023-05-12 09:06
Since #9052 tracks the only left undone issue, we close this issue now.

**Closed by lmatz** 2023-05-12 09:06 UTC
Labels: good first issue, help wanted, type/perf
