### ISSUE TITLE
feat: reduce the size of stored streaming metadata to avoid too large request to etcd

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#11072] opened 2023-07-19 11:38 UTC
### Is your feature request related to a problem? Please describe.

Related #7728

**Comment by BugenZhao** [comment] 2023-07-20 03:52
It looks like the large request is mainly caused by duplication of the `NodeBody` for a fragment with too many parallelisms (actors). I guess this can be resolved by introducing a (de)compression middleware for the protobuf values actually stored.

**Comment by yezizp2012** [comment] 2023-07-20 04:00
> It looks like the large request is mainly caused by duplication of the `NodeBody` for a fragment with too many parallelisms (actors). I guess this can be resolved by introducing a (de)compression middleware for the protobuf values actually stored.

Yes exactly. Previously I'm thinking of introducing a new field in `TableFragment` that stores only one copy of the `NodeBody` data and necessary distribution info, which can be used to generate the real running `StreamActor`. By simply adding some transform logic in meta, the duplicate part of `NodeBody` can be reduced. Add non-related to this issue, this will also pay off for switching to sql backend later on. WDUT?

**Comment by yezizp2012** [comment] 2023-10-10 05:37
The issue will not exist after SQL-backend meta store. Keep it open for record.

**Comment by yezizp2012** [comment] 2023-11-23 06:34
> > It looks like the large request is mainly caused by duplication of the `NodeBody` for a fragment with too many parallelisms (actors). I guess this can be resolved by introducing a (de)compression middleware for the protobuf values actually stored.
> 
> Yes exactly. Previously I'm thinking of introducing a new field in `TableFragment` that stores only one copy of the `NodeBody` data and necessary distribution info, which can be used to generate the real running `StreamActor`. By simply adding some transform logic in meta, the duplicate part of `NodeBody` can be reduced. Add non-related to this issue, this will also pay off for switching to sql backend later on. WDUT?

@shanicky is working on integration the transform logic to current `TableFragments` implementation, which was introduced for sql backends. The PR is otw.

**Comment by BugenZhao** [comment] 2024-07-05 08:52
> Done by #17315 ?

It's a quick solution, but I believe it should be enough for the goal in this issue. 😄 Feel free to close it.

**Closed** 2024-07-05 08:57 UTC
Labels: type/feature, component/meta, priority/high
