### ISSUE TITLE
nightly-20240521 perf degradation

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#16881] opened 2024-05-22 00:58 UTC
### Describe the bug

```
+---------------------------------------------------------------+--------------+------------+----------------------------------------------------+---------------------+-----------------------------+-------------------------------+
| BENCHMARK NAME                                                | EXECUTION ID | STATUS     | KEY METRICS                                        | FLUCTUATION OF BEST | FLUCTUATION OF LAST 10 DAYS | FLUCTUATION OF LAST EXECUTION |
+---------------------------------------------------------------+--------------+------------+----------------------------------------------------+---------------------+-----------------------------+-------------------------------+
| nexmark-q18-blackhole-medium-1cn                              |        29134 | Negative   | avg-source-output-rows-per-second                  | -23.91%             | -10.75%                     | -7.67%                        |
| nexmark-q20-blackhole-medium-1cn                              |        29144 | Negative   | avg-source-output-rows-per-second                  | -21.02%             | -14.18%                     | -14.37%                       |
```

<img width="1579" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/c8110c1b-ff3b-4e73-a986-aa8bc1e0e71c">

http://metabase.risingwave-cloud.xyz/dashboard/241-nexmark-blackhole-1cn-anti-affinity-rw-avg-source-throughput?start_date=2024-05-01&namespace=daily

### The version of RisingWave

nightly-20240521

### Additional context

https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240521

**Comment by fuyufjh** [comment] 2024-05-23 06:20
Could this be related to https://github.com/risingwavelabs/risingwave/pull/12570? @Little-Wallace  Can you please take a look?  Feel free to reassign if not so.

**Comment by Li0k** [comment] 2024-05-25 06:42
We note a certain amount of performance deterioration of nexmark due to the unanticipated compaction behavior. 
Compared with the previous test, we can find that no new compaction group was split during the test. 
Consequently, the compaction efficiency of the system was diminished, thereby giving rise to SST accumulation and reduced read performance.

In short, the change in compaction group split behavior caused a performance regression. Through the log , I found that the behavior of get_created_table_ids was different when using different meta backends. Moreover, the corresponding implementation of SQL backend lacked the sink table, thus causing the above problems.

**Comment by fuyufjh** [comment] 2024-05-30 07:32
Q18 and Q20's performance seem back to normal. Close this for now.

<img width="493" alt="Screenshot 2024-05-30 at 15 31 39" src="https://github.com/risingwavelabs/risingwave/assets/10192522/a4711a08-9a54-404d-96e1-ff2403d9d008">

<img width="489" alt="Screenshot 2024-05-30 at 15 32 18" src="https://github.com/risingwavelabs/risingwave/assets/10192522/88b30da6-1ea6-4545-9418-1e8a453db856">

**Closed by fuyufjh** 2024-05-30 07:32 UTC
Labels: type/bug, type/perf
