### ISSUE TITLE
bug: sysbench oltp insert 2022-02-08 test failed

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7802] opened 2023-02-09 02:38 UTC
### Describe the bug

Log: 
[https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$2[…]52Fsysbench-daily-test-20230208](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fsysbench-daily-test-20230208)

Grafana: 
[https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&[…]ar-namespace=sysbench-daily-test-20230208](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&from=1675892299000&to=1675892509000&to=&var-namespace=sysbench-daily-test-20230208)

Is the memory of batch queries fully under control now?
Feel free to reassign, @liurenjie1024  thanks!

**Comment by liurenjie1024** [comment] 2023-02-16 09:23
I've worked with @huangjw806 and found that this is caused by oom of compute node, which can be reproduced in kubebench:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/2771941/219322699-5f15a391-64c1-49f5-955f-908c71606267.png">

![image](https://user-images.githubusercontent.com/2771941/219322760-251d6f07-f26a-4b14-aefc-967ee00d37ae.png)

I think this is caused by unbounded queue in dml manager:

https://github.com/risingwavelabs/risingwave/blob/f14d0bfab0e4c0f2fbdaa21acf889d629064cec8/src/source/src/table.rs#L36

**Comment by liurenjie1024** [comment] 2023-02-16 09:25
cc @BugenZhao

**Comment by BugenZhao** [comment] 2023-02-16 09:34
> I think this is caused by unbounded queue in dml manager:

Yes, that could be a possible reason. But it has been always unbounded for a long time. 🤔

**Comment by liurenjie1024** [comment] 2023-02-16 09:42
> > I think this is caused by unbounded queue in dml manager:
> 
> Yes, that could be a possible reason. But it has been always unbounded for a long time. 🤔

We didn't do large scale insert before..

**Comment by lmatz** [comment] 2023-02-16 09:54
guess we should use bounded channel whenever possible the entire codebase? 

Induce worse performance at most? But avoid unrecoverable
errors

**Comment by BugenZhao** [comment] 2023-02-16 10:01
I'd like to fix this while doing some minor refactor here.

**Comment by liurenjie1024** [comment] 2023-02-20 01:50
In recent days' test, the error disappeared, so let's close it now.

**Closed by liurenjie1024** 2023-02-20 01:50 UTC
Labels: type/bug
