### ISSUE TITLE
decimal to double casting inconsistent with pg

### ISSUE THREAD

**Issue by wzzzzd** [risingwavelabs/risingwave#4691] opened 2022-08-17 05:51 UTC
**Describe the bug**
```
dev=> select (35521.32691633466::double = 35521.32691633467::double);
 ?column? 
----------
 t
(1 row)
dev=> select 35521.32691633466::double;
     ?column?      
-------------------
 35521.32691633467
(1 row)
```

In pg,
```
postgres=# select (35521.32691633466::double precision = 35521.32691633467::double precision);
 ?column? 
----------
 f
(1 row)
postgres=# select 35521.32691633466::double precision;
      float8       
-------------------
 35521.32691633466
(1 row)
```

**To Reproduce**
As above.

**Expected behavior**
RW should have the same query result as pg.

**Additional context**

**Comment by likg227** [comment] 2022-08-17 08:58
The bug comes from the wrong behavior of `decimal.to_f64()`.
```
    #[test]
    fn decimal_to_float() {
        let d = Decimal::from_str("35521.32691633466").unwrap();
        assert_eq!(d.to_f64().unwrap(), 35521.32691633466 as f64);
    }
```
```
thread 'types::decimal::tests::decimal_to_float' panicked at 'assertion failed: `(left == right)`
  left: `35521.32691633467`,
 right: `35521.32691633466`', src/common/src/types/decimal.rs:619:9
```

**Comment by xxchan** [comment] 2022-08-18 11:56
Maybe this is not a bug, because f64 has up to 15 decimal digits of precision 😄

**Comment by xiangjinwu** [comment] 2024-01-16 03:22
The issue was kept open to acknowledge a limitation due to dependency of the library. We may switch to another library for wider decimals.

Closing this as no action would be taken until that.

**Closed by xiangjinwu** 2024-01-16 03:22 UTC
Labels: type/bug, component/common, priority/low
