### ISSUE TITLE
v1.7.0-rc/nightly-20240201 source throughput down to 0 with non-shared PG CDC sources

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#14943] opened 2024-02-02 02:29 UTC
### Describe the bug

Run ch-benchmark with non-shared PG CDC sources with v1.7.0-rc/nightly-20240201

v1.7.0-rc: https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/187
nightly-20240201: https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/188

The buildkite pipeline jobs failed the data consistency check before they completed the data sync. Because the data consistency check would start after the source throughput down to 0 for 60 seconds.

[Grafana](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=ebec273b-0774-4ccd-90a9-c2a22144d623&var-namespace=ch-benchmark-pg-cdc-daily&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1706772925590&to=1706779097018)

![image](https://github.com/risingwavelabs/risingwave/assets/35356271/9505af68-5def-4af2-b90f-99c8ae6d4b68)
![image](https://github.com/risingwavelabs/risingwave/assets/35356271/b5409f15-4776-4b8d-8ac3-9989aa1a09c8)
![image](https://github.com/risingwavelabs/risingwave/assets/35356271/f18ff326-1a87-40fd-9bec-b270187268ef)

### The version of RisingWave

v1.7.0-rc
nightly-20240201

## nightly-20240201
- `752b5e0205cea397c51645cd39f12f3f24a5f06a` [refactor(meta): handle all stream client request in stream rpc manager (#14844)](https://github.com/risingwavelabs/risingwave/pull/14844)
- `725c6b05c62ac99001ab549c63fa8c4603752046` [test(connector): add debezium-mysql compatible test (#14891)](https://github.com/risingwavelabs/risingwave/pull/14891)
- `4c70f3dfd1f69174476bd3d08d48a708dd954f13` [test(connector): add debezium-pg compatible test (#14862)](https://github.com/risingwavelabs/risingwave/pull/14862)
- `9749e4c46f57e5c9738abfafe06fd6f8c0a1b8e0` [fix: initialize backup system parameter for in memory mode (#14921)](https://github.com/risingwavelabs/risingwave/pull/14921)
- `2437c082cdf26eecc9bd0229afc79335e7369a28` [test: add ruby client test (#14859)](https://github.com/risingwavelabs/risingwave/pull/14859)
- `ded73afefa465108d3a2baf559ec8380e4b4eda5` [fix(batch): fix sequential exchange (#14924)](https://github.com/risingwavelabs/risingwave/pull/14924)
- `6b3a3193b673dc24508eccaa0f8054db6fb716ab` [feat(telemetry): add `streaming_job_count` to meta telemetry report (#14878)](https://github.com/risingwavelabs/risingwave/pull/14878)
- `f621acb7af95db48780f0f7e6438c1a8315cdb24` [fix: using `alter source add column` on a table with conn will panic (#14922)](https://github.com/risingwavelabs/risingwave/pull/14922)
- `822190b1f3ca253b7eca31a2a9c47eda1d8f8827` [chore: update icelake (#14920)](https://github.com/risingwavelabs/risingwave/pull/14920)
- `b43a7b9e0d960f6a255c6559d2b0239cf49203d1` [feat: merge config for auto scale & enable auto scale  (#14873)](https://github.com/risingwavelabs/risingwave/pull/14873)
- `096570d106ee275244e2de3ff7df4a8705db6832` [refactor(connector): avoid anyhow in `AccessError` and avoid using `RwError` if possible (#14874)](https://github.com/risingwavelabs/risingwave/pull/14874)
- `5d43604d3e703fa0ed6594deb116ef2e6c660469` [fix(storage): assert no read version in storage reset (#14876)](https://github.com/risingwavelabs/risingwave/pull/14876)
- `fff9b79ba71487423291a1d48cb45994e15e2fa0` [chore(deps): bump rquickjs (#14897)](https://github.com/risingwavelabs/risingwave/pull/14897)
- `7834019899a0c4d86e0daa5101a42a91d003fe7d` [feat(log-store): add a vnode col in log store pk (#14599)](https://github.com/risingwavelabs/risingwave/pull/14599)
- `26297e583a44d59db8d2ed720e8420073b8dcb24` [chore: fix clippy (#14916)](https://github.com/risingwavelabs/risingwave/pull/14916)
- `c71efbb9346b83f18426f4535648b8e6a9ef6b58` [chore: Replace AUTO with ADAPTIVE for parallelism mode and table behavior (#14414)](https://github.com/risingwavelabs/risingwave/pull/14414)
- `309097204ccf67dbef9e2800077b463f5579a909` [refactor(over window): simplify `find_affected_ranges` and correct some corner cases (#14580)](https://github.com/risingwavelabs/risingwave/pull/14580)
- `344cf990870e9c73755f12021f9baaaf734a98d3` [feat: support sql func encrypt/decrypt  (#14717)](https://github.com/risingwavelabs/risingwave/pull/14717)
- `d22423077539b98e557814dcf1fb4f10d3b74e3a` [chore(dashboard): bump versions: Node.js to v20, Next.js to 14, typescript to 5.3.3 (#14913)](https://github.com/risingwavelabs/risingwave/pull/14913)
- `20fc87999a65c831e24006fff893604589e49547` [feat(grafana): improve actor info & source throughput panels (#14870)](https://github.com/risingwavelabs/risingwave/pull/14870)
- `32762399011b9ce332285e355899d0ede3b2c55f` [feat: support scaling in sql backend (#14757)](https://github.com/risingwavelabs/risingwave/pull/14757)
- `6acb999a32f22881bc22c74f6162256f43232eb6` [chore: update cherry pick version to release-1.7 (#14912)](https://github.com/risingwavelabs/risingwave/pull/14912)
- `73907050ca15dd1c98f6a342f793f6d96ada29cc` [refactor: replace ctor by linkme (#14814)](https://github.com/risingwavelabs/risingwave/pull/14814)
- `82d12773b924153bfc4c747e91791af939edbf02` [feat(expr): add support for make_date/time/timestamp (#14827)](https://github.com/risingwavelabs/risingwave/pull/14827)
- `9c874fe91c6f1b6c8301a94667e8c185337a2dc5` [chore: enable transactional cdc for mysql and postgres by default (#14899)](https://github.com/risingwavelabs/risingwave/pull/14899)
- `b65afa37f21c39d9fff512f030d02a0dde343f9a` [feat(cdc): support disable cdc backfill and only consumes from latest changelog (#14718)](https://github.com/risingwavelabs/risingwave/pull/14718)
- `d812316f1982edeab2527c07af418e08b3d8e8d0` [refactor: minor refactor on fragment graph building (#14560)](https://github.com/risingwavelabs/risingwave/pull/14560)
- `c2228ec862766df8364a914c796b5b660ebcff8f` [fix(tests): remove delete range runner test (#14889)](https://github.com/risingwavelabs/risingwave/pull/14889)
- `f21fb9b7915e7ed95b858ffd3d3d87ae20075c65` [feat(stream): read exactly 1 row if no snapshot read per barrier for arrangement backfill (#14842)](https://github.com/risingwavelabs/risingwave/pull/14842)
- `8cb91531cb1e8a9a49d835aacd4fad441874ba2f` [feat(sql-backend): disable etcd meta store initialization when sql backend is enabled (#14902)](https://github.com/risingwavelabs/risingwave/pull/14902)
- `7d0d43f6586c036642b3e5589ce6b24a878af077` [feat: support precompute partition for iceberg (#14710)](https://github.com/risingwavelabs/risingwave/pull/14710)

**Comment by StrikeW** [comment] 2024-02-04 06:52
Update: revert #14899 also reproduce the problem, investigating other PRs in the list.

**Comment by StrikeW** [comment] 2024-02-04 10:42
I found that the stream query in the passed job generated much less data compared with failed jobs.
<img width="800" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/7338536/2232b1a7-3114-4685-8c79-dc94743ca2d3">


And there is join amplification in the failed jobs: 
<img width="800" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/7338536/699cf856-b304-44a4-9bab-9a3207e831c7">

I suspect the workload has changed and I rerun the [pipeline](https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/196) with nightly-20240131 again, then it also experience [barrier piled up](https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1707042022090&orgId=1&to=1707043310106&var-component=All&var-datasource=ebec273b-0774-4ccd-90a9-c2a22144d623&var-instance=benchmark-risingwave&var-namespace=ch-benchmark-pg-cdc-daily-rerun-nightly-20240131&var-pod=All&var-table=All) as those failed jobs.

So I think the pipeline failure is **not** caused by the code change.  cc @lmatz if you have other information.

**Comment by lmatz** [comment] 2024-02-04 11:10
thanks for the findings, let us check if there is any changes on the pipeline side

**Comment by cyliu0** [comment] 2024-02-04 14:56
Recently, I've added the ch-benchmark q3 back to the pipeline. The q3 has been removed after this one https://github.com/risingwavelabs/risingwave/issues/12777

So I think it's still a problem?

**Comment by cyliu0** [comment] 2024-02-05 10:33
Reran the queries except q3 with v1.7.0-rc-1 passed https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/199

**Comment by cyliu0** [comment] 2024-02-06 03:34
Hit again for v1.7.0-rc-1 with following queries

CH_BENCHMARK_QUERY="q1,q2,q4,q5,q6,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q22"

https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/201
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&from=1707121771852&to=1707137671126&var-datasource=ebec273b-0774-4ccd-90a9-c2a22144d623&var-namespace=ch-benchmark-pg-cdc-20240205-085511&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All

**Comment by lmatz** [comment] 2024-02-19 02:56
> https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=ebec273b-0774-4ccd-90a9-c2a22144d623&var-namespace=ch-benchmark-pg-cdc-daily-20240207&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1707342785684&to=1707348581400

![SCR-20240219-f6h](https://github.com/risingwavelabs/risingwave/assets/5791930/1a64f80f-c5d2-4da5-beb8-c1219816b5e8)

Why the compaction duration is so high?

**Comment by StrikeW** [comment] 2024-02-19 03:12
> Hit again with nightly-20240207
> 
> https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc/builds/205#018d8597-b39f-48ed-bbea-9f1b27b911c8
> 
> https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=ebec273b-0774-4ccd-90a9-c2a22144d623&var-namespace=ch-benchmark-pg-cdc-daily-20240207&var-instance=benchmark-risingwave&var-pod=All&var-component=All&var-table=All&from=1707342785684&to=1707348581400

The symptom is same as the conclusion in https://github.com/risingwavelabs/risingwave/issues/14943#issuecomment-1925692637:
- Join amplification 
- Many L0 files
which causes barrier piled up and backpressures the the source.

**Comment by lmatz** [comment] 2024-02-19 03:51
> which causes barrier piled up and backpressures the the source.

Remove it from blockers for now.

> Join amplification
> Many L0 files

Join amplification is expected as it is determined by the nature of the query and data
but wonder why many L0 files

**Comment by fuyufjh** [comment] 2024-04-08 09:22
Ping, Any updates?

**Comment by lmatz** [comment] 2024-04-08 09:23
@cyliu0  could you run one more time but with more resources?

I think the point of this test is here is just to make sure that `non-shared PG CDC sources` don't block itself somehow,
but if the slowness/freeze is caused by query, then it does not matter.

**Comment by StrikeW** [comment] 2024-04-26 06:45
> 
> > but if the slowness/freeze is caused by query, then it does not matter.
> 
> It's caused by ch-benchmark q3 in this case.
> 
> @StrikeW Shall we keep this issue for future enhancements? Or close it now?

Optimize the query performance should be tracked by other issue. let's close this one.

**Closed by StrikeW** 2024-04-26 06:45 UTC
Labels: type/bug, found-by-chbenchmark-test

**Comment by cyliu0** [comment] 2024-05-08 06:10
The issue still exists with nightly-20240507. Which issue covered this right now? @StrikeW 
https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc-shared-source/builds/41#018f5655-3749-4029-a4b8-cc0c321eb18a
<img width="939" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/21d44bfe-bcf3-429e-8583-5130f3e89ad2">

**Comment by StrikeW** [comment] 2024-05-08 06:34
> The issue still exists with nightly-20240507. Which issue covered this right now? @StrikeW https://buildkite.com/risingwave-test/ch-benchmark-pg-cdc-shared-source/builds/41#018f5655-3749-4029-a4b8-cc0c321eb18a <img alt="image" width="939" src="https://private-user-images.githubusercontent.com/35356271/328773718-21d44bfe-bcf3-429e-8583-5130f3e89ad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDkzODQsIm5iZiI6MTcxNTE0OTA4NCwicGF0aCI6Ii8zNTM1NjI3MS8zMjg3NzM3MTgtMjFkNDRiZmUtYmNmMy00MjllLTg1ODMtNTEzMGYzZTg5YWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA2MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MjFiZGMzYTlhNDkwZGZkNDk4ODY2ZDIwMTkxYjQ2YmNhYjY4ZmExYzM2OTVmMzk4Y2UxZWEzMDBiOGEwNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5P9kmPd7mW7Fdb548CfeDhJC_IzsnAnRDWlu8sgdvNY">

There is no new issue for the performance problem.

The source is backpressured and could you confirm that the CN is configured with 16GB memory?
<img width="600" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/7338536/0da07d59-a108-43be-a745-be4e1fa35dc9">

It seems the bottleneck is in the state store due to the amount of L0 files and lead to higher sync duration.
https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?from=1715140652391&orgId=1&to=1715143112711&var-component=All&var-datasource=P2453400D1763B4D9&var-instance=benchmark-risingwave&var-namespace=tpc-20240508-035346&var-pod=All&var-table=All

**Comment by StrikeW** [comment] 2024-05-08 06:44
I think this should be a performance issue instead of functionality bug, so I suggest you can create a new issue for it and post to perf working group.
