### ISSUE TITLE
performance regression (for debug & single binary) of backtrace capturing after bumping toolchain on macOS

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#6131] opened 2022-10-31 18:24 UTC
### Describe the bug

I found risingwave becomes significantly slow on my mac. e.g., `e2e_test/batch/basic/array.slt.part` takes 30+ seconds. After `git bisect`, I found the regression happens after https://github.com/risingwavelabs/risingwave/pull/6025.

### Additional context

~~@skyzh can't reproduce. CI also works fine. Need someone else to confirm it.~~ Confirmed it happens on debug & single binary mode.

- https://github.com/rust-lang/rust/issues/104388

**Comment by skyzh** [comment] 2022-10-31 18:26
Can you collect some perf result on that? Thanks!

**Comment by chenzl25** [comment] 2022-10-31 18:54
I also found this regression on debug mode and Sysbench QPS dropped to almost zero. However everything works well on release mode.

**Comment by skyzh** [comment] 2022-10-31 19:23
single-binary doesn't work well, while multi-binary looks good. Is there anything that might goes wrong with the madsim update? cc @wangrunji0408

**Comment by skyzh** [comment] 2022-10-31 19:38
<img width="740" alt="image" src="https://user-images.githubusercontent.com/4198311/199095584-ce9d7c85-19d5-461d-a1e4-a1836eb13954.png">

And ok_or_else seems to consume significant amount of CPU time.

**Comment by skyzh** [comment] 2022-10-31 19:40
<img width="922" alt="image" src="https://user-images.githubusercontent.com/4198311/199095778-c608b03f-9412-47ff-900b-50bbc71d3224.png">

... because backtrace is slow to create

**Comment by skyzh** [comment] 2022-10-31 20:25
In multi-binary:

```
backtrace captured in 1ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
backtrace captured in 0ms
```

In single-binary:

```
backtrace captured in 393ms
backtrace captured in 369ms
backtrace captured in 370ms
backtrace captured in 365ms
backtrace captured in 362ms
```

Probably a bug with the Rust compiler, but I would still recommend not returning so many errors.

**Comment by skyzh** [comment] 2022-10-31 20:25
Related function:

```
    pub fn get_schema_by_name(&self, db_name: &str, schema_name: &str) -> Result<&SchemaCatalog> {
        self.get_database_by_name(db_name)?
            .get_schema_by_name(schema_name)
            .ok_or_else(|| {
                let x = Instant::now();
                let err = CatalogError::NotFound("schema", schema_name.to_string()).into();
                println!("backtrace captured in {}ms", x.elapsed().as_millis());
                err
            })
    }
```

**Comment by skyzh** [comment] 2022-11-01 00:55
The suspicious thing is the dwarf region in the binary.

On 2022-07-29:

```
objdump target/debug/risingwave  --dwarf=frame | wc -l
     371
```

On 2022-10-16:

```
objdump target/debug/risingwave  --dwarf=frame | wc -l
 14671494
```

**Comment by skyzh** [comment] 2022-11-01 00:55
Shall we file a bug report to rust-lang? (Though I believe this is more of an LLVM bug / LLVM upgrade)

**Comment by skyzh** [comment] 2022-11-01 01:56
I would suggest keep this issue open while changing frontend to return Option instead of error.

**Comment by BugenZhao** [comment] 2022-11-01 07:15
> I would suggest keep this issue open while changing frontend to return Option instead of error.

I think most of the errors generated in the frontend are for responding to the user, which cannot be avoided.

**Comment by fuyufjh** [comment] 2022-11-01 07:28
Is it caused by capturing the stacktrace?

**Comment by skyzh** [comment] 2022-11-01 15:59
> I think most of the errors generated in the frontend are for responding to the user, which cannot be avoided.

No. The e2e test cases that timed out should not have any user-facing error. All tables exist.

> Is it caused by capturing the stacktrace?

Yes.

**Comment by skyzh** [comment] 2022-11-01 16:00
There seems to be some new features in Rust / LLVM that generates a special kind of debug info DWARF, which contains stack unwinding region information. In debug mode it's just slow to rewind.

**Comment by fuyufjh** [comment] 2022-11-02 01:29
It's not a big issue but still affected the developer's experience 🥲 What is our solution? 

1. Wait for rust community to fix it. (Don't know how much it will take)
2. Refactor the code that captures the stack-trace into error
3. Any other ideas?

**Comment by skyzh** [comment] 2022-11-02 02:38
> Wait for rust community to fix it.

I don't think that's something to be fixed. It looks more like a feature that provides better backtrace.

> Refactor the code that captures the stack-trace into error

I think a fix is going on to change them to cheaper CatalogEror.

**Comment by fuyufjh** [comment] 2022-11-02 02:39
cc. @BowenXiao1999

**Comment by BugenZhao** [comment] 2022-11-02 02:45
I've opened an issue for this -> #6157.

**Comment by xiangjinwu** [comment] 2022-11-04 08:11
Backtrace capturing is not only slower, but can also lead to a segfault: #6205

**Comment by xxchan** [comment] 2022-11-10 14:27
The performance problem is much better now. It took me 200s to run `slt-all` for multi-binary and 250s for single-binary (when the issue opened it was forever).

**Comment by xiangjinwu** [comment] 2022-11-14 03:48
Closing this issue in favor of #4077 and #6205.

The slowness is acknowledged by the doc of [`Backtrace::capture`](https://doc.rust-lang.org/std/backtrace/struct.Backtrace.html#method.capture), and our take on it would be to avoid unnecessary backtrace capture via #4077.

The segfault is worse and tracked by #6205.

**Comment by skyzh** [comment] 2022-11-15 04:26
TImeout is a separate issue. reopen.

**Closed** 2023-04-08 20:16 UTC
Labels: type/bug
