### ISSUE TITLE
bug(frontend): `INSERT INTO t1 (v2, v1)` ignores specified columns list

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#4046] opened 2022-07-20 07:35 UTC
**Describe the bug**
```
dev=> create table t1 (v1 int, v2 int);
CREATE_TABLE
dev=> insert into t1 values (1, 2);
INSERT 0 1
dev=> select * from t1;
 v1 | v2
----+----
  1 |  2
(1 row)

dev=> insert into t1 (v1, v2) values (3, 4);
INSERT 0 1
dev=> insert into t1 (v2, v1) values (5, 6);
INSERT 0 1
dev=> select * from t1;
 v1 | v2
----+----
  3 |  4
  5 |  6
  1 |  2
(3 rows)
```

Specified columns is not handled in `bind_insert`.

**Comment by BugenZhao** [comment] 2022-07-20 07:53
Seems the columns are totally ignored? 😄

**Comment by yezizp2012** [comment] 2022-07-20 07:55
> Seems the columns are totally ignored? 😄

Yes, QwQ

**Comment by fuyufjh** [comment] 2022-08-25 09:42
Any updates?

**Comment by xiangjinwu** [comment] 2022-08-26 02:39
> Any updates?

Not yet. Fixing similar issues in other parts ...

**Comment by CAJan93** [comment] 2022-10-06 12:34
I would like to have a look at it if that is fine by you. Please let me know if you are already working on this @xiangjinwu. AFAIK this is not a time-critical issue. It does not have a milestone attached to it, right? 

Just to reiterate. When running the following statements

```SQL 
create table t (v1 int, v2 int);
insert into t values (1, 2);
insert into t (v1, v2) values (3, 4);
insert into t (v2, v1) values (5, 6);
select * from t;
```

We expect

```
 v1 | v2
----+----
  1 | 2
  3 | 4
  6 | 5
```

but instead receive 

```
 v1 | v2
----+----
  5 | 6
  3 | 4
  1 | 2
```

This is because we are currently ignoring the columns. This is also why we can run incorrect statements, like 

```SQL 
insert into t (x, y) values (0, 0);
# Postgres error: column "x" of relation "t" does not exist 
insert into t (v1, v1) values (0, 0);
# Postgres error: column "v1" specified more than once
```

**Comment by BugenZhao** [comment] 2022-10-08 04:45
May related:
- #2672

**Comment by CAJan93** [comment] 2022-10-17 13:40
Current PR is still work in progress, because I am working on a cloud related issue at the moment.

**Comment by CAJan93** [comment] 2022-10-27 17:55
I talked about this issue with @nanderstabel. We would propose to split up this issue in two parts: 

1. Support the specified column insertion order. I.e. queries as such should work/throw errors

```
create table t1 (v1 int, v2 int);
insert into t1 (v1, v2) values (5, 6);
insert into t1 (v2, v1) values (5, 6);
insert into t1 (v1) values (5, 6); // error 
insert into t1 (v1234, v2) values (5, 6); // error unknown column
...
```

3. Support `NULL` values if the user did not define enough values 

```
create table t1 (v1 int, v2 int);
insert into t1 (v1) values (5); // v2 should implicitly be NULL
```

IMHO 1.) and 2.) are two distinct problems and supporting them in one PR is quite a headache (at least for me). Would this approach be fine by you guys? 

Maybe we should do some more discussions regarding 2.) and what the expected behaviour is

```
create table t1 (v1 int, v2 int);
insert into t1 (v1) values (5);  // v2 should be NULL 
insert into t1 values (5);  // v2 should be NULL? Do we allow this even though the user did not explicitly define what is null? 
```

**Comment by xiangjinwu** [comment] 2022-10-28 03:06
> supporting them in one PR is quite a headache

In most cases it is actually encouraged to break problems into smaller ones. No need to worry about not solving it in one go.

> what the expected behaviour is

Follow PostgreSQL's behavior or raise a reason not to do so (e.g. increased complexity with rare/deprecated usage). For this specific case, PostgreSQL does allow it and fills `v2` with `null` ([ref](https://www.postgresql.org/docs/current/dml-insert.html#:~:text=INSERT%20INTO%20products%20VALUES%20(1%2C%20%27Cheese%27)%3B)):
> The second form is a PostgreSQL extension. It fills the columns from the left with as many values as are given, and the rest will be defaulted.

**Comment by CAJan93** [comment] 2022-10-31 13:47
Perfect. Thank you for the clarification. Opening https://github.com/risingwavelabs/risingwave/issues/6128

**Comment by CAJan93** [comment] 2022-11-02 13:06
First version of the PR https://github.com/risingwavelabs/risingwave/pull/5697 is ready for review. I still have a few minor questions which I point out in the PR. Please let me know what you think.

**Comment by fuyufjh** [comment] 2022-11-21 07:32
closed by https://github.com/risingwavelabs/risingwave/pull/5697

**Closed by fuyufjh** 2022-11-21 07:32 UTC
Labels: type/bug, good first issue, help wanted, component/frontend, user-facing-changes, difficulty/simple
