### ISSUE TITLE
implement array_agg

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7763] opened 2023-02-08 04:40 UTC
https://www.postgresql.org/docs/9.5/functions-aggregate.html
https://docs.snowflake.com/en/sql-reference/functions/array_agg.html

Requested by POC

**Comment by xiangjinwu** [comment] 2023-02-08 09:43
Already supported:
```
dev=> with t(v1) as (values (7), (1), (4)) select array_agg(v1) from t;
 array_agg 
-----------
 {7,1,4}
(1 row)
```

**Comment by CAJan93** [comment] 2023-02-08 09:57
Quick question: According to the [snowflake docs](https://docs.snowflake.com/en/sql-reference/functions/array_agg.html) `array_agg`

> Returns the input values, pivoted into an ARRAY. If the input is empty, an empty ARRAY is returned.

So, I would expect an empty array `{}` as an output of the following queries: 

```SQL 
create table t (v1 integer) ;
with t2(v1) as (select * from t) select array_agg(v1) from t2;
 array_agg
-----------

(1 row)
```

Instead I get no output. I assume this is by design, right?

**Comment by xiangjinwu** [comment] 2023-02-08 10:09
In PostgreSQL:
> It should be noted that except for `count`, these functions return a null value when no rows are selected. In particular, `sum` of no rows returns null, not zero as one might expect, and `array_agg` returns null rather than an empty array when there are no input rows. The `coalesce` function can be used to substitute zero or an empty array for null when necessary.

It actually took us extra effort to support this null semantic.

**Comment by xiangjinwu** [comment] 2023-02-10 04:07
Is there specific testing query that is not passing by current implementation? If not, we can close this issue.

As for empty vs null, as PostgreSQL doc suggested, the empty semantic can be expressed as `coalesce(array_agg(v1), array[]::int[])`.

**Closed** 2023-02-10 04:10 UTC
Labels: good first issue, help wanted, priority/high
