### ISSUE TITLE
bug: recover_backfill_state panic

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#19138] opened 2024-10-26 06:30 UTC
### Describe the bug

The stream job being backfilled is SINK INTO TABLE. It includes NOW.

`"panicInfo": "panicked at src/stream/src/executor/backfill/no_shuffle_backfill.rs:607:13:\nassertion `left == right` failed\n  left: true\n right: false"`

The compute node has been scaled down from 6C to 2C. I suspect it's related because the assertion mentions: `All vnode partitions should have same state (no scale-in supported).`

### The version of RisingWave

v2.0.2

**Comment by zwang28** [comment] 2024-10-26 08:03
> Currently scaling is not supported for background backfilling job

So this is an expected error. 
It will be better if we don't have to drop the affected sinks to recover the cluster. @kwannoel

**Comment by kwannoel** [comment] 2024-10-27 13:55
Opened an issue here  https://github.com/risingwavelabs/risingwave/issues/19142 for the corresponding feature. Closing as this is not a bug.

**Closed by kwannoel** 2024-10-27 13:55 UTC
Labels: type/bug
