### ISSUE TITLE
ch_benchmark_pg_cdc data verification failed with meta node pod-failure fault

### ISSUE THREAD

**Issue by xuefengze** [risingwavelabs/risingwave#15245] opened 2024-02-26 04:59 UTC
### Describe the bug

The experiment made the meta pod unavailable for 20 seconds. https://buildkite.com/risingwave-test/chaos-mesh/builds/616

> Pod Failure Chaos Experiment would change the image of each container in the target Pod to the "pause image", which is a special image that does not perform any operations.

```
{
    "url": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
    "database-name": "postgres",
    "database-checksum": -2276467997646561433,
    "table-checksums": [
        {
            "url": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
            "table-name": "ch_benchmark_q1",
            "table-checksum": -2276467997646561433,
            "table-rows": 15
        }
    ]
}
{
    "url": "postgres://root:@127.0.0.1:4567/dev",
    "database-name": "dev",
    "database-checksum": -5986507887034328951,
    "table-checksums": [
        {
            "url": "postgres://root:@127.0.0.1:4567/dev",
            "table-name": "ch_benchmark_q1",
            "table-checksum": -5986507887034328951,
            "table-rows": 15
        }
    ]
}
```
same faults as with https://github.com/risingwavelabs/risingwave/issues/15190.

### The version of RisingWave

nightly-20240225

**Comment by lmatz** [comment] 2024-02-26 05:01
link https://github.com/risingwavelabs/risingwave/issues/15190

**Comment by StrikeW** [comment] 2024-04-08 09:59
Confirm with @xuefengze the issue is verification fail, close this one and tracked the issue by #15312

**Closed by StrikeW** 2024-04-08 09:59 UTC
Labels: type/bug, found-by-chaos-mesh, block-release-v1.8
