### ISSUE TITLE
bug: `MaterializeBuffer` index out of bounds: the len is 0 but the index is 7

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8136] opened 2023-02-23 05:50 UTC
### Describe the bug

```
2023-02-22T21:55:18.490121614Z stderr F thread 'risingwave-streaming-actor' panicked at 'index out of bounds: the len is 0 but the index is 7', src/common/src/array/data_chunk.rs:353:30
```

```
2023-02-22T21:55:22.664343948Z stdout F Actor 15: `CREATE TABLE bid (\"auction\" BIGINT, \"bidder\" BIGINT, \"price\" BIGINT, \"channel\" CHARACTER VARYING, \"url\" CHARACTER VARYING, \"date_time\" TIMESTAMP, \"extra\" CHARACTER VARYING) WITH (connector = 'nexmark', nexmark.table.type = 'Bid', nexmark.split.num = '12', nexmark.min.event.gap.in.ns = '50000') ROW FORMAT NATIVE` [4.852087122s]
```

[risingwave-compute-default-0_rwc-3-chaosmesh-20230222-214344_compute-e973b3f0d447d58805ddf0c196e2a82ac9514414023c6ba3dcdcd113105e8e2a.csv](https://github.com/risingwavelabs/risingwave/files/10810619/risingwave-compute-default-0_rwc-3-chaosmesh-20230222-214344_compute-e973b3f0d447d58805ddf0c196e2a82ac9514414023c6ba3dcdcd113105e8e2a.csv)

Cloudwatch log:
https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Frwc-3-chaosmesh-20230222-214344/log-events/ip-10-0-94-78.ap-southeast-1.compute.internal-risingwave.var.log.containers.risingwave-compute-default-0_rwc-3-chaosmesh-20230222-214344_compute-e973b3f0d447d58805ddf0c196e2a82ac9514414023c6ba3dcdcd113105e8e2a.log$3Fstart$3D-43200000

Slack notification:
https://risingwave-labs.slack.com/archives/C048NM5LNKX/p1677106608007479

Buildkite:
https://buildkite.com/risingwave-test/longevity-chaos-mesh/builds/189#01867b14-df61-4e15-889e-bbc722661bc4

**Comment by BugenZhao** [comment] 2023-02-23 08:53
Seems caused by the `MaterializeBuffer`. cc @wcy-fdu Could you please take a look?

https://github.com/risingwavelabs/risingwave/blob/4d5c4feb98e4861a541928cbe08c2149a75f8527/src/stream/src/executor/mview/materialize.rs#L277-L289

**Comment by BugenZhao** [comment] 2023-02-23 08:57
Does it mean that there's an empty input chunk? Looks like if we build a data chunk from an empty chunk builder, we'll get no columns in the chunk instead of empty columns with the correct schema. Is this expected? cc @liurenjie1024 

BTW, I'm considering whether it'll be better to also enable the schema check wrapper in production. 🤨

https://github.com/risingwavelabs/risingwave/blob/4d5c4feb98e4861a541928cbe08c2149a75f8527/src/stream/src/executor/wrapper.rs#L71-L123

**Comment by fuyufjh** [comment] 2023-03-22 09:17
cc. @BugenZhao

**Comment by BugenZhao** [comment] 2023-03-23 07:56
Seems like a problem with the connector's schema. Since there's no reproduction and we've enabled schema check in the release profile (#8711), let's close this issue now.

**Closed by BugenZhao** 2023-03-23 07:56 UTC
Labels: type/bug
