### ISSUE TITLE
Bug: longevity test compute pod OOM

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#11977] opened 2023-08-31 02:27 UTC
Longevity Test Result:

```
Today's date:2023-08-31
Result               FAIL                
Pipeline Message     @Nightly run all stateful nexmark queries with 16000 throughput
TestBed              kubebench/kafka-stream
RW Version           nightly-20230830    
Test Start time      2023-08-30 14:13:14 
Test End time        2023-08-31 02:16:35 
Namespace            reglngvty-20230830-140803
Queries              nexmark_q3, nexmark_q4, nexmark_q5, nexmark_q7, nexmark_q8, nexmark_q9, nexmark_q12, nexmark_q15, nexmark_q16, nexmark_q17, nexmark_q18, nexmark_q19, nexmark_q20
User/Feature         default             
Grafana Metric       https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20230830-140803&from=1693404794000&to=1693448195000
Grafana Logs         https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&var-namespace=reglngvty-20230830-140803&from=1693404794000&to=1693448195000
Buildkite Job        https://buildkite.com/risingwave-test/longevity-kubebench/builds/595
Crash Container logs https://rw-qa-artifacts-public.s3.us-east-1.amazonaws.com/longevity/595_logs.txt
report               https://rw-qa-artifacts-public.s3.us-east-1.amazonaws.com/longevity/595_report.txt


================================================================================
Restarted/Crashed Containers Details 
================================================================================
CONTAINER crashed/Restarted: benchmark-risingwave-compute-c-1 restart_count:1  phase:Running status:True
```

CN pod OOM:
<img width="909" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/29391315/d8a7dc73-c5fd-4a0c-97ae-2814b070f37c">

**Comment by fuyufjh** [comment] 2023-08-31 05:54
Even though the symptom is OOM, I think the root cause is because of the drastic fluctuation of barriers. 

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/512e5756-ce63-414d-9578-1ace2dc975f9)

Some metrics are obviously abnormal, but I don't know which are causes and which are results.

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/f31f1748-57da-4b50-b75a-545844205f9a)

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/f0d29739-aeb2-4dc9-8486-74ce901cf45e)

![image](https://github.com/risingwavelabs/risingwave/assets/10192522/6fcd12c4-9985-491b-8cf2-263b00d580ae)

**Comment by lmatz** [comment] 2023-08-31 06:45
Can I conclude as the following:
1. The compactor does not have enough memory -> reject compaction tasks since 5:00 -> more data to be read by CN so that the barrier may stuck due to more storage IO -> more likely to OOM if a certain part of memory is not strictly controlled
2. OOM is caused by certain operators that do not control their memory usage strictly due to some unknown reason

Since we want to test these stressed scenarios, I suppose we should not increase the memory of the compactor in the test?

**Comment by huangjw806** [comment] 2023-09-01 02:32
It seems that compute pod OOM occurs more often at 50000 throughput.

```
"!!! longevity Result!!!"
Today's date:2023-09-01
Result               FAIL                
Pipeline Message     @Nightly run all stateful nexmark queries with 50000 throughput
TestBed              kubebench/kafka-stream
RW Version           nightly-20230831    
Test Start time      2023-08-31 14:14:46 
Test End time        2023-09-01 02:18:17 
Namespace            reglngvty-20230831-140930
Queries              nexmark_q3, nexmark_q4, nexmark_q5, nexmark_q7, nexmark_q8, nexmark_q9, nexmark_q12, nexmark_q15, nexmark_q16, nexmark_q17, nexmark_q18, nexmark_q19, nexmark_q20
User/Feature         default             
Grafana Metric       https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&var-namespace=reglngvty-20230831-140930&from=1693491286000&to=1693534697000
Grafana Logs         https://grafana.test.risingwave-cloud.xyz/d/liz0yRCZz1/log-search-dashboard?orgId=1&var-data_source=Logging:%20test-useast1-eks-a&var-namespace=reglngvty-20230831-140930&from=1693491286000&to=1693534697000
Buildkite Job        https://buildkite.com/risingwave-test/longevity-kubebench/builds/597
Crash Container logs https://rw-qa-artifacts-public.s3.us-east-1.amazonaws.com/longevity/597_logs.txt
report               https://rw-qa-artifacts-public.s3.us-east-1.amazonaws.com/longevity/597_report.txt


================================================================================
Restarted/Crashed Containers Details 
================================================================================
CONTAINER crashed/Restarted: benchmark-risingwave-compute-c-0 restart_count:4  phase:Running status:True
CONTAINER crashed/Restarted: benchmark-risingwave-compute-c-1 restart_count:2  phase:Running status:True
CONTAINER crashed/Restarted: benchmark-risingwave-compute-c-2 restart_count:1  phase:Running status:True
```

**Comment by fuyufjh** [comment] 2023-09-07 02:46
After removing Q16 from test set, it's much more stable than before.

https://buildkite.com/risingwave-test/longevity-kubebench/builds/610#018a6a96-07fa-4e01-b5ac-d7dd3300a900

<img width="700" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/b4069cdb-0205-46b0-ae67-2f942e371865">

<img width="949" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/02edebb9-64ac-4409-bbb7-76f4d27e4fec">

**Comment by wcy-fdu** [comment] 2023-10-10 05:47
I will continue to investigate the causes of OOM later.

**Comment by wcy-fdu** [comment] 2023-10-18 02:52
Can we reproduce this OOM on the latest image? This image is 20230830, which is v1.1 and at that time we had not collected core dump files yet, so we can not get the heap file to analyze the memory usage.

And We have also merged many OOM-related fixes(both compaction side and compute side) in the past two months, so I suggest to check again after reproducing with the latest image. cc @huangjw806

**Comment by huangjw806** [comment] 2023-10-18 02:58
> Can we reproduce this OOM on the latest image? 

We are still running longevity test daily. If new OOM problems are found, I will update here.

**Comment by huangjw806** [comment] 2023-10-19 03:12
If the kafka source throughput is 20k, OOM will occur in CN. You can take a look at the nightly longevity pipeline.
https://buildkite.com/risingwave-test/longevity-kubebench/builds/739

**Comment by wcy-fdu** [comment] 2023-10-19 10:27
After investigating the newest heap file, I found that it's materialized executor, along with it's StateTableInner takes up a lot of memory, I guess adding spill anytime for materialized executor can alleviate this problem to a certain extent. I've retested with the spilled image, let's wait for the results.

<img width="1011" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/58715567/024b75b3-f264-4506-a436-583064aab8fc">

**Comment by fuyufjh** [comment] 2023-11-08 09:07
Should be fixed by https://github.com/risingwavelabs/risingwave/pull/12028. Feel free to reopen if recurs.

**Comment by fuyufjh** [comment] 2023-11-09 02:40
According to our Slack discussion, the root cause might be both rdkafka (no issue yet) and lack of MemTable spill (#12777). 

Thanks a lot for the hard work by @wcy-fdu

**Closed** 2023-11-17 08:36 UTC
Labels: type/bug, found-by-longevity-test
