### ISSUE TITLE
tpch performance degradation for v1.10.0-rt.3

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#17681] opened 2024-07-15 01:05 UTC
### Describe the bug

http://metabase.risingwave-cloud.xyz/question/26990-rw-avg-source-throughput-release?start_date=2024-03-01&testbed=medium-1cn-affinity&workload=tpch

<img width="1898" alt="image" src="https://github.com/user-attachments/assets/e5fd291b-4a1e-412b-8eeb-99254cb6c7e4">

http://metabase.risingwave-cloud.xyz/dashboard/508-tpch-affinity-1cn-rw-avg-source-throughput?start_date=2023-09-24

<img width="1570" alt="image" src="https://github.com/user-attachments/assets/22efabf2-9499-4c54-a54c-f1cd23b32b2e">

### The version of RisingWave

v1.10.0-rt.3

**Comment by lmatz** [comment] 2024-07-16 01:24
Q1 halved from 600K/s to 300K/s

This is weird because Q1 only has a simple aggregation where the number of group-by keys is 4.
Not much memory usage, no cache misses and I believe it was bottlenecked by the source connector or network bandwidth.

Let's run the old image once

**Comment by lmatz** [comment] 2024-07-16 04:05
likely to be some issue in the infra instead of kernel

**Comment by lmatz** [comment] 2024-07-16 06:16
we close the issue as it is caused by the change of ebs gp2 to gp3

**Closed** 2024-07-16 06:22 UTC
Labels: type/bug, type/perf, block-release-v1.10
