### ISSUE TITLE
Failed to execute sysbench select random points

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#8194] opened 2023-02-27 07:19 UTC
### Describe the bug

sysbench error:
![image](https://user-images.githubusercontent.com/35356271/221497690-4df3d5ce-26f3-41f5-8344-84c59359ed7b.png)

[buildkite pipeline jobs](https://buildkite.com/risingwave-test/sysbench/builds/294#01868f8a-a253-4e7c-8b50-9d3e9dc0ce16)

[grafana](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&from=1677446546000&to=1677446709000&to=&var-namespace=sysbench-daily-test-20230226)

[meta log](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fsysbench-daily-test-20230226/log-events/ip-10-0-87-239.ap-southeast-1.compute.internal-risingwave.var.log.containers.benchmark-risingwave-meta-0_sysbench-daily-test-20230226_meta-66dee488445bc2cb78ad88e9d3f938ffb26fe27c4c207c7bf9e33f6cf83f078b.log)

**Comment by liurenjie1024** [comment] 2023-02-28 07:25
It seems that it's caused by random compute node restart, and not caused by oom:
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/2771941/221782848-9f4378f8-3dfd-4611-9f8e-f89776d8f13d.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/2771941/221782895-3e593874-d2aa-4d3c-bb0f-29e3b59b20a4.png">

And it doesn't happen again, so I guess it's random failure. Let's close it first.

**Closed by liurenjie1024** 2023-02-28 07:25 UTC
Labels: type/bug
