### ISSUE TITLE
`DROP SOURCE <name> CASCADE` does not work

### ISSUE THREAD

**Issue by mikechesterwang** [risingwavelabs/risingwave#13085] opened 2023-10-26 11:48 UTC
### Describe the bug

The following statements are executed in order
1. trying to drop source 
```sql
dev=> DROP SOURCE drivers;
ERROR:  QueryError: Permission denied: PermissionDenied: Fail to delete source `drivers` because 1 other relation(s) depend on it
```

2. trying to drop source using CASCADE mode, and the result **shows no problem**
```sql
dev=> DROP SOURCE drivers CASCADE;
DROP_SOURCE
```

3. show sources, seems the source still exists.
```sql
dev=> SHOW SOURCES;
  Name   
---------
 drivers
 rides
(2 rows)
```

4. no jobs in progress
```sql
dev=> SHOW JOBS;
 Id | Statement | Progress 
----+-----------+----------
(0 rows)
```

5. trying to drop the source again, got the same error, indicating the source still exists
```sql
dev=> DROP SOURCE drivers;
ERROR:  QueryError: Permission denied: PermissionDenied: Fail to delete source `drivers` because 1 other relation(s) depend on it
```

6. drop the mview depending on the source, and then run drop source again. The source is finally dropped
```sql
dev=> DROP MATERIALIZED VIEW driver_status;
DROP_MATERIALIZED_VIEW

dev=> DROP SOURCE drivers;
DROP_SOURCE

dev=> SHOW SOURCES;
 Name  
-------
 rides
(1 row)
```

### How did you deploy RisingWave?

docker-compose

### The version of RisingWave

```
dev=> SELECT version();
                                  version                                   
----------------------------------------------------------------------------
 PostgreSQL 9.5-RisingWave-1.3.0 (c4c31bdc5e8763ae65ec23293e8c07bdfd4ab4df)
(1 row)
```

**Comment by chenzl25** [comment] 2023-10-27 10:44
Could you please provide your concrete sqls, since I can't reproduce it. Recently we have a fix https://github.com/risingwavelabs/risingwave/pull/12745. But your version seems to have this fix.

**Comment by fuyufjh** [comment] 2023-11-08 10:11
Ping @mikechesterwang ?

**Comment by chenzl25** [comment] 2023-11-13 08:57
Already fixed by https://github.com/risingwavelabs/risingwave/pull/12731

**Closed by chenzl25** 2023-11-13 08:57 UTC
Labels: type/bug
