### ISSUE TITLE
`HashJoinExecutor` panics on compute node in nexmark query

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#8354] opened 2023-03-06 06:55 UTC
### Describe the bug

`HashJoinExecutor` panics on compute node in nexmark query
```
compute-node-0  | 2023-03-06T06:06:08.717480Z  INFO risingwave_storage::hummock::event_handler::hummock_event_handler: update to hummock version: 20, epoch: 3987706209304576
compute-node-0  | thread 'thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'assertion failed: self.left_size() >= ret.len()cannot convert ArrayImpl::Int64 to concrete type Int32', ', /ebs/risingwave/src/common/src/hash/key.rs:541:17
compute-node-0  | src/common/src/array/mod.rs:466stack backtrace:
compute-node-0  | :1
compute-node-0  | thread 'risingwave-streaming-actor' panicked at 'assertion failed: self.left_size() >= ret.len()', /ebs/risingwave/src/common/src/hash/key.rs:541:17
compute-node-0  | risingwave-streaming-actor' panicked at 'assertion failed: self.left_size() >= ret.len()', /ebs/risingwave/src/common/src/hash/key.rs:541:17
compute-node-0  | thread 'risingwave-streaming-actor' panicked at 'assertion failed: self.left_size() >= ret.len()', /ebs/risingwave/src/common/src/hash/key.rs:541:17
compute-node-0  |    0: rust_begin_unwind
compute-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
compute-node-0  |    1: core::panicking::panic_fmt
compute-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
compute-node-0  |    2: core::panicking::panic
compute-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:114:5
compute-node-0  |    3: <risingwave_common::hash::key::FixedSizeKeySerializer<_> as risingwave_common::hash::key::HashKeySerializer>::append
compute-node-0  |              at ./ebs/risingwave/src/common/src/hash/key.rs:541:17
compute-node-0  |    4: risingwave_common::hash::key::serialize_array_to_hash_key
compute-node-0  |              at ./ebs/risingwave/src/common/src/hash/key.rs:636:9
compute-node-0  |    5: risingwave_common::hash::key::HashKey::build_from_hash_code
compute-node-0  |              at ./ebs/risingwave/src/common/src/hash/key.rs:130:13
compute-node-0  |    6: risingwave_common::hash::key::HashKey::build
compute-node-0  |              at ./ebs/risingwave/src/common/src/hash/key.rs:112:12
compute-node-0  |    7: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::eq_join_oneside::{{closure}}
compute-node-0  |              at ./ebs/risingwave/src/stream/src/executor/hash_join.rs:887:20

```

### To Reproduce

```
create source auction (
      id INTEGER,
      item_name VARCHAR,
      description VARCHAR,
      initial_bid INTEGER,
      reserve INTEGER,
      date_time TIMESTAMP,
      expires TIMESTAMP,
      seller INTEGER,
      category INTEGER)
    with (
      connector = 'nexmark',
      nexmark.table.type = 'Auction'
    );

    create source bid (
      auction INTEGER,
      bidder INTEGER,
      price INTEGER,
      channel VARCHAR,
      url VARCHAR,
      date_time TIMESTAMP,
      extra VARCHAR)
    with (
      connector = 'nexmark',
      nexmark.table.type = 'Bid'
    );

    create source person (
      id INTEGER,
      name VARCHAR,
      email_address VARCHAR,
      credit_card VARCHAR,
      city VARCHAR,
      state VARCHAR,
      date_time TIMESTAMP)
    with (
      connector = 'nexmark',
      nexmark.table.type = 'Person'
    );
CREATE MATERIALIZED VIEW nexmark_q7 AS
SELECT
      B.auction,
      B.price,
      B.bidder,
      B.date_time
    FROM
      bid B
    JOIN (
      SELECT
        MAX(price) AS maxprice,
        window_end as date_time
      FROM
        TUMBLE(bid, date_time, INTERVAL '10' SECOND)
      GROUP BY
        window_end
    ) B1 ON B.price = B1.maxprice
    WHERE
      B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
      AND B1.date_time;
```

**Comment by soundOfDestiny** [comment] 2023-03-06 06:56
cc. @fuyufjh

**Comment by soundOfDestiny** [comment] 2023-03-06 08:14
The query is incorrect but I think risingwave should report an `Err` earlier and should not panic.

**Comment by fuyufjh** [comment] 2023-03-06 08:51
@yuhao-su Please take a look

**Comment by yuhao-su** [comment] 2023-03-06 09:41
This is caused by source providing data that does not match the schema. This can potentially cause error/panic in many unexpected positions.

I prefer to fix this by handling this behavior on source instead of all other stream executors.

```
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 13000027E5: column 0 should be Some("Int32"), while stream chunk gives Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:35:33
```

**Comment by st1page** [comment] 2023-03-06 09:51
So our nexmark source does not consider the schema and datatypes in `create souce` statement and just gives a fixed schema?

**Comment by fuyufjh** [comment] 2023-03-07 08:23
> @yuhao-su Please take a look

Feel free to reassign 🥰

**Comment by BugenZhao** [comment] 2023-03-22 09:06
So maybe we should validate the schema when creating the nexmark sources? I've also encountered this in #8618.

BTW, do you run this query without debug assertions? Maybe we should include the schema check wrapper also in release profile.

**Closed** 2023-05-19 10:09 UTC
Labels: type/bug
