### ISSUE TITLE
Tracking: Improve debezium format in source

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#7890] opened 2023-02-13 13:53 UTC
Debezium connect is a widely-adopted way to capture changes in various databases (MySQL, PostgreSQL, Oracle, ...). We have initial support for debezium but there are still some limitations. It is time to improve it as more and more use cases come up. This is the list of missing features order by priority:

- [x] #7892
- [ ] Support parsing kafka message key for upsert use cases. Currently we only look at the kafka message value.
- [x] #7904
- [x] #7940
- [ ] Support schema changes in source table (low priority and require further design)

Some key points I noticed when playing around debezium:
- Debezium will monitor changes for a given database and emit change events to kafka topics configured with a `topic_prefix`:
  - Topic `<topic_prefix>` contains the schema change events (triggered by DDL) for the database. See [here](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-schema-change-topic) for more details.
  - Topic `<topic_prefix>.<database/schema>.<table>` contains data change events (triggered by DML) **for the specific table in the database/schema**.  See [here](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-events) for more details.
- The CDC event is represented by a kafka message (See [here](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-change-events-key) for more details)
  - The kafka message key contains the primary key of the table
  - The kafka message value contains payload of the changes. Payload is different for different types of data change (e.g. create/update/delete).
  - There is a schema field in both message key and value to describe the types of the key/value payload for parsing.
- For DEBEZIUM AVRO format, the AVRO schema is used to decode kafka message key/value, which is different from the table schema. (See [here](https://debezium.io/documentation/reference/stable/configuration/avro.html) for more details)
- For debezium version >=2.0.0, confluent schema registry support is no longer included by default but can be added via plugins. For testing, I suggest we use debezium version 1.9 to avoid headaches on setting up the envrionment.

**Comment by StrikeW** [comment] 2023-02-13 15:56
I think the Debezium mentioned in the issue is referred to the [kafka connector](https://www.risingwave.dev/docs/current/create-source-cdc/) that ingest CDC events from a kafka topic, rather than the connector node, right?

**Comment by tabVersion** [comment] 2023-02-13 17:27
> I think the Debezium mentioned in the issue refers to the [kafka connector](https://www.risingwave.dev/docs/current/create-source-cdc/) that ingest CDC events from a kafka topic, rather than the connector node, right? Just want to make things clear.

Yes, just offer you a wider picture. But the feature requests for the connector node still exist.

**Comment by tabVersion** [comment] 2023-05-02 15:43
will continue tracking the second item in https://github.com/risingwavelabs/risingwave/issues/9268
close this one.

**Closed as completed by tabVersion** 2023-05-02 15:43 UTC
Labels: no-issue-activity, type/feature, A-connector, P-high
