### ISSUE TITLE
bug: incorrect result in streaming outer join

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#2420] opened 2022-05-10 17:31 UTC
**Describe the bug**
```sql
yuhao=> create table t2(v1 int, v2 int);
CREATE_TABLE
yuhao=> create table t1(v1 int, v2 int);
CREATE_TABLE
yuhao=> create materialized view mv3 as select t1.v1 as v11, t2.v1 as v21 from t1 full outer join t2 on t1.v1 = t2.v1;
CREATE_MATERIALIZED_VIEW
yuhao=> insert into t2 values(3, 3);
INSERT 0 1
yuhao=> delete from t2 where v2 = 3;
DELETE 1
yuhao=> insert into t1 values(3, 3);
INSERT 0 1
yuhao=> select * from mv3;
 v11 | v21 
-----+-----
(0 rows)

```

The current select result is `null null` while the correct result should be `3 null`

This happens because of the incorrect implementation of the **not matched** situation: When a `JoinRow` was inserted, a `JoinStateEntry` will be created, but when the same `JoinRow` is deleted, only the `JoinRow` will be removed from `JoinStateEntry` while the `JoinStateEntry` itself will not be removed. 

To fix this, we should notice both cases when the outer join matching the other side should be considered **not matched**: 1)  no matched `JoinStateEntry` 2) matched `JoinStateEntry` but no matched rows

**Comment by yuhao-su** [comment] 2022-05-10 17:34
Would you like to take a look at this and do some fixes in #2387. I think I made this mistake before. Thanks! @jon-chuang .

**Comment by st1page** [comment] 2022-05-10 18:31
maybe we can do the fix after #2387 merged? suggest splitting to 2 different PR.

**Comment by yuhao-su** [comment] 2022-05-10 18:32
> maybe we can do the fix after #2387 merged? suggest splitting to 2 different PR.

Sure. Let's do it later then.

**Comment by jon-chuang** [comment] 2022-05-10 19:39
Should add a regression test for this

**Comment by jon-chuang** [comment] 2022-05-10 19:56
Isn't the right implementation to remove the `JoinStateEntry` when there are no more rows matching?

**Comment by yuhao-su** [comment] 2022-05-10 20:17
> Isn't the right implementation to remove the `JoinStateEntry` when there are no more rows matching?

If you mean remove the `JoinStateEntry` when deleting all `JoinRows`, we need to fetch the remote data from S3 to determine whether all `JoinRows` was deleted. However by design, we tend to fetch remote on read instead of on write. This means better not to try decide removing `JoinStateEntry` on delete. The entry will eventually be removed by LRU policy.

**Comment by jon-chuang** [comment] 2022-05-10 20:58
Actually hashjoin also had more bugs:
1. apply dec_degree after checking the zero_degree condition on Op::Delete, not before
2. send outer side null only once

in addition to:
send outer side null exactly once if not matched after iterating over matched_rows.

Thanks for pointing out the bug and helping find the new ones.

**Comment by jon-chuang** [comment] 2022-05-10 21:16
@yuhao-su , since I couldn't be sure which of the bugs caused the output you observed, I've fixed all the above issues in the PR and added a regression test for sending multiple times, and for sending non matching after deleting matching to existing outer join test.

**Comment by yuhao-su** [comment] 2022-05-11 01:15
> Actually hashjoin also had more bugs:
> 
> 1. apply dec_degree after checking the zero_degree condition on Op::Delete, not before
> 2. send outer side null exactly once
> 
> in addition to: send outer side null exactly once if not matched after iterating over matched_rows.
> 
> Thanks for pointing out the bug and helping find the new ones.

I did noticed those bugs. Thanks for fixing!

**Closed as completed** 2022-05-11 01:44 UTC
Labels: type/bug
