### ISSUE TITLE
Bug: customer usecase frontend transport error on GCP

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#12508] opened 2023-09-25 04:27 UTC
1. Customer usecase pipeline error:
```


e2etest/dragonpass/query.slt                                 .. [BEGIN]
--
  | \| e2etest/dragonpass/./drop.slt.part                           .. [OK] in 284 ms
  | \| e2etest/dragonpass/./dategen-source.slt.part                 .. [OK] in 78 ms
  | \| e2etest/dragonpass/./mvs.slt.part                            .. [FAILED]
  |  
  | failed to run `e2etest/dragonpass/query.slt`
  |  
  | Caused by:
  | statement failed: db error: ERROR: QueryError: internal error: transport error
  | [SQL] CREATE INDEX IF NOT EXISTS station_detail_idx ON station_detail(window_start);
  | at e2etest/dragonpass/./mvs.slt.part:74
  | at e2etest/dragonpass/query.slt:3


```
pipeline link: https://buildkite.com/risingwave-test/customer-usecases/builds/253#018aca87-638d-4e83-aa53-0b50f2782dde

2. grafana log link: [frontend log](https://grafana.test.risingwave-cloud.xyz/explore?orgId=1&left=%7B%22datasource%22:%22P5EF386EDA43AEBD1%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P5EF386EDA43AEBD1%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnamespace%3D%5C%22rwc-g1hb58f8udfmuahcupp59npkph-customer-usercases-21743%5C%22,%20app%3D~%5C%22risingwave-frontend-default%5C%22%7D%20%7C%3D%20%60CREATE%20INDEX%20IF%20NOT%20EXISTS%20card_usage_idx%20ON%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D)

NOTE: The same case was successfully run on AWS. I am not sure whether it is caused by gcp cloud network problems.

**Comment by yezizp2012** [comment] 2023-09-25 05:28
Seems like recovery was triggered in meta and there were some dns resolution issues found in both meta and compute node side. It must be caused by gcp cloud network problems.
```
2023-09-25 12:14:54.154	
{"timestamp":"2023-09-25T04:14:54.008412235Z","level":"WARN","fields":{"message":"refresh meta member client failed gRPC error (The service is currently unavailable): error trying to connect: dns error: failed to lookup address information: Name or service not known"},"target":"risingwave_rpc_client::meta_client"}
```

**Comment by yezizp2012** [comment] 2023-10-17 09:03
Suspected to be a cloud network problem, close it first.

**Closed by yezizp2012** 2023-10-17 09:03 UTC
Labels: type/bug
