### ISSUE TITLE
discussion: integrate pre-push hook to do `risedev check`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7722] opened 2023-02-06 10:48 UTC
### Is your feature request related to a problem? Please describe.

When discussing with @cyliu0 he suggested to introduce a pre-push hook to run some simple checks before push to GitHub. This sounds good to me and we may start from `./risedev check`, which takes less than 1 minute on average.

However, a problem is `git` doesn't allow checking in files in `.git/hooks`. Perhaps https://github.com/rhysd/cargo-husky can be helpful.

**Comment by BugenZhao** [comment] 2023-02-06 13:44
Any motivation for this? IIRC, we added a pre-**commit** hook long ago (https://github.com/risingwavelabs/risingwave-legacy/pull/2289) and removed it soon due to the bad developing experience.

It is worth pointing out that pushing something to GitHub does not always mean that it's associated with an open PR: maybe the developer just wants to have a remote backup. If the motivation is to reduce CI cost, we may suffer inconvenience in these cases.

**Comment by cyliu0** [comment] 2023-02-07 03:17
Now the main and nightly docker build CI pipeline failed a lot. This leads to our daily testing can't run smoothly for the recent two weeks. In order to improve the main branch stability and reduce the CI cost, I got two suggestions. The first one is git pre-push hook. This hook running duration must be finished in 3-5 minutes. The second one is more important to run the main test CI pipelines after the PR is ready to merge, in our case, it's when we got two approvals for the PR. I don't suggest we should run the CI pipelines for every push of the PR, it will increase our CI cost a lot. You can always use `--no-verify` to skip hooks. A git pre-push hook to reduce the simple and stupid problems and a CI pipeline for the final check before merging, this combo will solve the main branch and nightly docker image stability problems.

**Comment by fuyufjh** [comment] 2023-02-07 03:21
> Any motivation for this? IIRC, we added a pre-**commit** hook long ago ([risingwavelabs/risingwave-legacy#2289](https://github.com/risingwavelabs/risingwave-legacy/pull/2289)) and removed it soon due to the bad developing experience.

Yes, I know that story. But pre-push hook sounds like a reasonable compromise. For me, >90% cases of `git push` is to create or update a pull request.

**Comment by BugenZhao** [comment] 2023-02-07 03:31
> Now the main and nightly docker build CI pipeline failed a lot.

These failures are impossible to reproduce in 3-5 minutes: it's not a trivial compile error that can be incrementally checked on the developer's machine. Take the frequent failures we encountered these days as an example, deterministic e2e requires at least 3 minutes to build and 10 minutes to run, and building the docker image takes at least 20 minutes.

> The second one is more important to run the main test CI pipelines after the PR is ready to merge, in our case, it's when we got two approvals for the PR.

I can't see any improvement as it seems to simply transfer the cost from the main branch to the PR branch. A more critical thing is, PRs are merged sequentially as we're relying on the merge-queue. As we're having more and more PR getting merged each day, increasing the check time before a PR gets merged will significantly reduce the work efficiency.

**Comment by cyliu0** [comment] 2023-02-07 03:45
> > Now the main and nightly docker build CI pipeline failed a lot.
> 
> These failures are impossible to reproduce in 3-5 minutes: it's not a trivial compile error that can be incrementally checked on the developer's machine. Take the frequent failures we encountered these days as an example, deterministic e2e requires at least 3 minutes to build and 10 minutes to run, and building the docker image takes at least 20 minutes.
This hook is not going to run all the test and build works. `This hook running duration must be finished in 3-5 minutes` means we should limit the hook workload. I don't expect the hook will solve every problem. I hope it will solve simple and stupid problems like a trivial compile error.
> 
> > The second one is more important to run the main test CI pipelines after the PR is ready to merge, in our case, it's when we got two approvals for the PR.
> 
> I can't see any improvement as it seems to simply transfer the cost from the main branch to the PR branch. A more critical thing is, PRs are merged sequentially as we're relying on the merge-queue. As we're having more and more PR getting merged each day, increasing the check time before a PR gets merged will significantly reduce the work efficiency.
Of course, it will increase the PR opening duration. But we do need the main branch and nightly build stability for daily testing. And if we have more and more PRs every day, the main branch stability is also important to every contributor.

**Comment by BugenZhao** [comment] 2023-02-07 03:46
In order to improve test stability, we can only increase the frequency of test runs. Therefore, if CI costs have to be reduced, it will not be possible to run more tests and it will be unlikely to have any effect.

> This leads to our daily testing can't run smoothly for the recent two weeks.

I guess what you're really concerning is the stability of building and running the nightly Docker image. 🤔 This is because we're massively refactoring the configuration framework these days. For this case, PR authors should be required to trigger docker image builds on BuildKite manually, but "whether it's necessary" cannot be simply decided. Besides, if the CLI args are changed, it's also impossible to check usage in other repositories.

**Comment by cyliu0** [comment] 2023-02-07 03:52
> Therefore, if CI costs have to be reduced, it will not be possible to run more tests and it will be unlikely to have any effect.

The goal is not to save CI costs. The CI cost is the factor we should consider when we want to improve our workflow. More tests coming and growing costs are facts we need to face in the future. But we need to get our money's worth.

**Comment by BugenZhao** [comment] 2023-02-07 03:52
> I hope it will solve simple and stupid problems like a trivial compile error.

Isn't this covered by the PR workflow? Why do we need another mechanism for simply checking the compile error?

> And if we have more and more PRs every day, the main branch stability is also important to every contributor.

I can say that the only "main branch stability" that affects work efficiency is flaky tests, which are caused by some concurrency edge cases. This is also clearly a scenario with no shortcuts: if we want to find them out ASAP, the only way is to run it more times or increase the test duration. This does not contribute the goal of "reducing the CI cost".

**Comment by xxchan** [comment] 2023-02-07 13:18
+1 for bugen's opinions. 

Note the process is:
1. local check & test
2. PR workflow
3. main workflow
4. cron job

If the problem is the stability of main/cron build, pre-push hook simply WON'T HELP, because such problems are already prevented in an earlier phase. An earlier step can only do a subset of the tests performed in the next step.

Maybe pre-push hook can save some PR CI costs, so that motivation would be somewhat reasonable to me. (A similar, maybe better measure is https://github.com/risingwavelabs/risingwave/issues/7727)

**Comment by xxchan** [comment] 2023-02-07 13:27
... And I think main CI is not very unstable recently, we'd better to make it clear what's real problem and then figure out a solution.

**Closed** 2023-02-20 03:12 UTC
Labels: type/feature
