### ISSUE TITLE
bug(sqllogictest): unreacheable code sqllogictest-engines-0.21.0/src/postgres/simple.rs:46:22

### ISSUE THREAD

**Issue by KeXiangWang** [risingwavelabs/risingwave#17830] opened 2024-07-27 01:51 UTC
### Describe the bug

As titled.

### Error message/log

```text
2024-07-27T01:44:17.805588Z  INFO sqllogictest::system_command: system command executed command="psql -c \"\n  DROP TABLE IF EXISTS shipments1;\n  CREATE TABLE shipments1 (\n    shipment_id SERIAL NOT NULL PRIMARY KEY,\n    order_id SERIAL NOT NULL,\n    origin VARCHAR(255) NOT NULL,\n    destination VARCHAR(255) NOT NULL,\n    is_arrived BOOLEAN NOT NULL\n  );\n  ALTER SEQUENCE public.shipments1_shipment_id_seq RESTART WITH 1001;\n  INSERT INTO shipments1\n  VALUES (default,10001,'Beijing','Shanghai',false),\n         (default,10002,'Hangzhou','Shanghai',false),\n         (default,10003,'Shanghai','Hangzhou',false);\n\"" status=ExitStatus(unix_wait_status(0)) stdout="INSERT 0 3\n" stderr="NOTICE:  table \"shipments1\" does not exist, skipping\n"
thread 'main' panicked at /Users/kexiang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqllogictest-engines-0.21.0/src/postgres/simple.rs:46:22:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

### To Reproduce

Prepare your own postgres and mysql.

In risedev.yml, add following config (update with your own config):
```
      - use: postgres
        port: 5432
        user-managed: true
        application: "connector"
        database: "mydb"
        password: "postgrespw"
        user: postgresuser
      - use: mysql
        port: 3306
        user-managed: true
        user: root
        password: "123456"
        database: mydb
```

In `src/risedevtool/src/risedev_env.rs`, 
- at line 113, add `let database = &c.database;`
- at line 118, add `writeln!(env, r#"PGDATABASE="{database}""#,).unwrap();`

It's fixed in https://github.com/risingwavelabs/risingwave/pull/17829

Start RW:
```
./risedev d
```

Run test
```
./risedev slt e2e_test/source/cdc_inline/alter/cdc_table_alter.slt
```

### The version of RisingWave

RW version
```
dev=> select version();
                       version                        
------------------------------------------------------
 PostgreSQL 13.14.0-RisingWave-1.11.0-alpha (unknown)
(1 row)
```
the most recent main branch.

```
> sqllogictest --version
sqllogictest-bin 0.21.0
```

```
rustc --version
rustc 1.78.0-nightly (4a0cc881d 2024-03-11)
```

**Comment by xxchan** [comment] 2024-07-29 04:34
Sorry, I cannot reproduce this on my machine. 

Could you please hack `sqllogictest` and install locally to print more information of the `unreachable` for debugging?

**Comment by xxchan** [comment] 2024-07-29 06:37
The problem is because:
- tokio-postgres 0.7.11 added a new variant to SimpleQueryMessage
- sqllogictest-rs@0.21.0's Cargo.lock uses 0.7.10
	- If we install binary release, it will be fine. But we failed to create a binary release, so it will install from source 🤡 (fixed now)
	- When installing from source, Cargo.lock is ignored by default, unless explicit `--locked` (https://github.com/rust-lang/cargo/issues/7169). So 0.7.11 is used.

**Closed by xxchan** 2024-07-29 06:37 UTC
Labels: type/bug
