### ISSUE TITLE
bug: wrong parsed timestamp from json

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#16097] opened 2024-04-02 16:18 UTC
### Describe the bug

When parsing json value to timestamp:

```json
{
	"before": null,
	"after": {
	    "id": 13,
        "example_timestamp_tz": 63072000000000000
    },
	"source": {
		"table": "pathmetadata"
	},
	"op": "c",
	"ts_ms": 1707225270445
}
```

Value `63072000000000000` should be parsed as `1972-01-01 00:00:00`. But RW parses it as `3968-09-03 02:00:00.000 +0200`, which is `63072007200`.

### To Reproduce

example json:

```json
{
	"before": null,
	"after": {
	    "id": 13,
        "example_timestamp_tz": 63072000000000000
    },
	"source": {
		"table": "pathmetadata"
	},
	"op": "c",
	"ts_ms": 1707225270445
}
```

### Expected behavior

Value `63072000000000000` should be parsed as `1972-01-01 00:00:00`.

**Comment by tabVersion** [comment] 2024-04-02 16:57
seems the time unit inference gets this wrong, cc @xiangjinwu 
https://github.com/risingwavelabs/risingwave/blob/a285394047c86b03702f0d5a12fd6dd3daa41620/src/common/src/cast/mod.rs#L60-L70

**Comment by xiangjinwu** [comment] 2024-04-03 04:23
To repeat myself one more time, this is by design and documented:

https://docs.risingwave.com/docs/current/sql-create-source/#debezium-json
> Note that if you are ingesting data of type `timestamp` or `timestamptz` in RisingWave, the upstream value must be in the range of `[1973-03-03 09:46:40, 5138-11-16 09:46:40] (UTC)`. The value may be parsed and ingested incorrectly without warning.

@MrCroxx Could you provide more context on this specific use case? How is the source created and how do we know if the unit is s / ms / us / ns?

> Value `63072000000000000` should be parsed as `1970-01-01 00:00:00`. But RW parses it as `3968-09-03 02:00:00.000 +0200`, which is `63072007200`.

This claim is problematic as well. How could a later date have a smaller value?

**Comment by xiangjinwu** [comment] 2024-04-03 04:40
Sync'ed offline:

`63072000000000000` in this case is expected to be `1972-01-01T00:00:00Z` (in `ns`, not `1970`) but is parsed as `3968-09-03T00:00:00Z` (in `us`).

**Comment by fuyufjh** [comment] 2024-04-03 06:26
> seems the time unit inference gets this wrong, cc @xiangjinwu
> 
> https://github.com/risingwavelabs/risingwave/blob/a285394047c86b03702f0d5a12fd6dd3daa41620/src/common/src/cast/mod.rs#L60-L70

This solution looks acceptable, but is too general for some cases, for example

1. If it's using the direct CDC, we can actually make sure the format must be milliseconds after https://github.com/risingwavelabs/risingwave/pull/16119
2. If users specifiy a parsing behavior manually via some `WITH` settings, we should follow that.

**Comment by tabVersion** [comment] 2024-04-16 09:29
close this issue as completed

**Closed by tabVersion** 2024-04-16 09:29 UTC
Labels: type/bug
