### ISSUE TITLE
common: value encoding for list and struct is slower than key encoding

### ISSUE THREAD

**Issue by Gun9niR** [risingwavelabs/risingwave#5713] opened 2022-10-08 10:53 UTC
In #5165, we have benchmarked the ser / de of  key / value encoding. We discovered that ser/de of value encoding for `List` and `Struct` are slower than key encoding. The perf gap comes from the use of `protobuf`.

https://github.com/risingwavelabs/risingwave/blob/3cd78e7aedd94d52206d5ff30999856f4876db29/src/common/src/util/value_encoding/mod.rs#L74-L104

Possible solutions:

- Just use key encoding instead
- Explore more efficient interfaces of protobuf
- Find some other data format

Related context:

- [flamegraph](https://github.com/risingwavelabs/risingwave/pull/5165#issuecomment-1238942829)
- [bench result](https://github.com/risingwavelabs/risingwave/pull/5165#issuecomment-1272276772)

**Comment by xiangjinwu** [comment] 2022-10-10 08:50
Should be fixed by #4672

**Comment by waruto210** [comment] 2022-10-17 13:06
The perf of ser/de of value encoding for List and Struct has improved a lot by #5880, but deserialization of value encoding for List is still slower than key encoding.
Should I close this issue?

**Comment by Gun9niR** [comment] 2022-10-17 13:54
Should we investigate why de is still slower before closing this issue?

**Comment by waruto210** [comment] 2022-10-18 07:58
> Should we investigate why de is still slower before closing this issue?

According to #5897, this should be caused by lazy allocation.

**Closed** 2022-10-18 08:27 UTC
Labels: component/common, type/perf
