### ISSUE TITLE
Support throttling an already created source/table

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#12997] opened 2023-10-23 06:16 UTC
Currently user can use `SET RW_STREAMING_RATE_LIMIT = <rate_limit_per_actor>` to rate limit source/table created in the session but we don't have a way to throttle a specific source/table if it is not created with `SET RW_STREAMING_RATE_LIMIT`.

This is useful when there are data accumulated in the source and processing these data in one barrier without throttling will cause endless OOM.

**Comment by hzxa21** [comment] 2023-10-23 06:16
cc @tabVersion @fuyufjh @chenzl25 @kwannoel

**Comment by hzxa21** [comment] 2023-10-23 06:17
@tabVersion and I was thinking whether we can easily support throttling an already created source by introducing a config to limit "number of messages allowed" per barrier in source. It seems that this needs a bigger refactoring and I think that we can adopt the existing FlowControlExeuctor approach.

**Comment by fuyufjh** [comment] 2023-10-23 06:20
Agree. 

In my mind, the user-interface is via altering a property of source. Also, to achieve this, we need to make `RW_STREAMING_RATE_LIMIT` a property of source

**Comment by chenzl25** [comment] 2023-10-23 07:14
Technically, we can modify the `rate_limit` property in the `ChainNode` of the Mv and restart the cluster to make it work. That is the simplest way.

**Comment by tabVersion** [comment] 2023-10-23 07:53
> Technically, we can modify the rate_limit property in the ChainNode of the Mv and restart the cluster to make it work. That is the simplest way.

I think making it an individual executor will give us more freedom placing it anywhere in the graph if we want to make some quick fix. I am drafting a rfc explaining how what the expected behavior is.

**Comment by fuyufjh** [comment] 2023-10-23 07:55
> > Technically, we can modify the rate_limit property in the ChainNode of the Mv and restart the cluster to make it work. That is the simplest way.
> 
> I think making it an individual executor will give us more freedom placing it anywhere in the graph if we want to make some quick fix. I am drafting a rfc explaining how what the expected behavior is.

FYI. This part is perhaps in done in https://github.com/risingwavelabs/risingwave/pull/11919 and https://github.com/risingwavelabs/risingwave/pull/12295

**Comment by tabVersion** [comment] 2023-10-23 08:51
> > > Technically, we can modify the rate_limit property in the ChainNode of the Mv and restart the cluster to make it work. That is the simplest way.
> > 
> > 
> > I think making it an individual executor will give us more freedom placing it anywhere in the graph if we want to make some quick fix. I am drafting a rfc explaining how what the expected behavior is.
> 
> FYI. This part is perhaps done in #11919 and #12295

That's true. The work left is on the `ChainNode` and the frontend, giving more ways to modify the control rate.

**Comment by BugenZhao** [comment] 2023-10-24 04:03
I'm unsure if it's really necessary to make it so "general", that is, utilizing the Alter MV approach to achieve the rate modification. From my prospective, we may simply wrap each executor with a `RateLimitExecutor` **without** the awareness in the persisted stream graph. A (developer) system parameter will encode rate limit settings for all actors (if present), which is subsribeded by those `RateLimitExecutor`.

**Comment by tabVersion** [comment] 2023-10-25 05:05
> I'm unsure if it's really necessary to make it so "general", that is, utilizing the Alter MV approach to achieve the rate modification. From my prospective, we may simply wrap each executor with a `RateLimitExecutor` **without** the awareness in the persisted stream graph. A (developer) system parameter will encode rate limit settings for all actors (if present), which is subscribed by those `RateLimitExecutor`.

I don't think it is necessary in most cases but it is essential to reduce the data into the cluster, preventing from OOM loop.
let's make it a dev tool, a risectl func, rather than a common prop in the first version.

**Comment by kwannoel** [comment] 2023-10-25 13:59
Hi, seems @tabVersion is working on this issue. Could you please share more of the overall direction you will take?

**Comment by BugenZhao** [comment] 2023-10-26 05:49
> Could you please share more of the overall direction you will take?

+1. So what's the plan for updating the flow control rate online?

**Comment by tabVersion** [comment] 2023-10-31 06:37
> > Could you please share more of the overall direction you will take?
> 
> +1. So what's the eventual plan for updating the flow control rate online?

I am proposing a config change solution, risectl will send a `Throttle` Command to apply throttle args on given `table_id`or`source_id` related actors. PR #13166

**Comment by tabVersion** [comment] 2023-11-01 07:51
As `FlowControl` Executor does not require an additional actor_id, I think all Source exec (including fetch exec) and Chain exec will get the following `FlowControl` exec after https://github.com/risingwavelabs/risingwave/pull/13057.
Thus, the throttle config change proposed in #13166 is also valid for existing tables(and requires an upgrade)

**Comment by kwannoel** [comment] 2023-11-02 07:41
> I'm unsure if it's really necessary to make it so "general", that is, utilizing the Alter MV approach to achieve the rate modification. From my prospective, we may simply wrap each executor with a `RateLimitExecutor` **without** the awareness in the persisted stream graph. A (developer) system parameter will encode rate limit settings for all actors (if present), which is subscribed by those `RateLimitExecutor`.

I'm thinking if we can let the system parameter be granular enough. Seems kind of weird, because system parameter is system-wide setting.

Whereas here, we may want to specify rate limit for a specific stream job, rather than the whole stream graph.

**Comment by kwannoel** [comment] 2023-11-02 07:45
Actually I think the two approach can be compatible? Both have their usecases.

- System parameter to throttle entire stream graph, if we don't know error source, and just want to make it stable ASAP.
- Config change once we have narrowed down the source.

Within the flow control executor we have the following behaviour:
1. One subscriber which will update the rate_limit, if there's change to system setting.
2. Config change support as done by @tabVersion  in https://github.com/risingwavelabs/risingwave/pull/13166

**Comment by tabVersion** [comment] 2024-01-09 09:08
will continue to push forward after closing https://github.com/risingwavelabs/risingwave/issues/14384

**Comment by tabVersion** [comment] 2024-03-06 09:09
will continue moving the throttle inside source exec and backfill exec

**Comment by tabVersion** [comment] 2024-05-14 09:20
https://github.com/risingwavelabs/risingwave/pull/15948 close as completed

**Closed by tabVersion** 2024-05-14 09:20 UTC
Labels: type/feature
