### ISSUE TITLE
Meta failover crashes Hummock 

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#6534] opened 2022-11-22 14:54 UTC
### Describe the bug

 I am currently able to do failover handling from one node to another (see [PR](https://github.com/risingwavelabs/risingwave/pull/6466)). A meta node will do a dummy stand-by (do nothing) if it is a follower and start its services if it is a leader. If a follower becomes a leader it will start its services and then crash because of a Hummock issue. I am not sure if this is really related to the storage engine or if we just in general assume that we only ever had one meta service running. 
 
 In the log below you see the successful failover handling. The node was a follower and got elected to leader after the previous leader crashed. The new leader starts its services and hummock crashes

```
2022-11-22T14:36:49.883674Z  INFO risingwave_meta::rpc::server: leader_info: MetaLeaderInfo { node_address: "127.0.0.1", lease_id: 8455512798517591123 }
2022-11-22T14:36:49.885355Z  INFO risingwave_meta::rpc::server: Cannot update lease if not leader
2022-11-22T14:36:49.886918Z  INFO risingwave_meta::rpc::server: lease exists and leader continues term
2022-11-22T14:36:50.027435Z  INFO risingwave_meta::rpc::server: leader_info: MetaLeaderInfo { node_address: "127.0.0.1", lease_id: 8455512798517591123 }
2022-11-22T14:36:50.029527Z  INFO risingwave_meta::rpc::server: Cannot update lease if not leader
2022-11-22T14:36:50.031877Z  WARN risingwave_meta::rpc::server: Detected that leader is dead
2022-11-22T14:36:50.033194Z  INFO risingwave_meta::rpc::server: Deleted leader lease
2022-11-22T14:36:50.171241Z  INFO risingwave_meta::rpc::server: running an election...
2022-11-22T14:36:50.174637Z  INFO risingwave_meta::rpc::server: lease_id: 1644958123911963089
2022-11-22T14:36:50.174663Z  INFO risingwave_meta::rpc::server: leader_info: MetaLeaderInfo { node_address: "127.0.0.1", lease_id: 1644958123911963089 }
2022-11-22T14:36:50.174682Z  INFO risingwave_meta::rpc::server: lease_info: MetaLeaseInfo { leader: Some(MetaLeaderInfo { node_address: "127.0.0.1", lease_id: 1644958123911963089 }), lease_register_time: 1669127810, lease_expire_time: 1669127820 }
2022-11-22T14:36:50.174698Z  INFO risingwave_meta::rpc::server: We have no leader
2022-11-22T14:36:50.177482Z  INFO risingwave_meta::rpc::server: Election done. Entering term
2022-11-22T14:36:50.177512Z  INFO risingwave_meta::rpc::server: This node currently is a leader
2022-11-22T14:36:50.177550Z  INFO risingwave_meta::rpc::server: Node is leader. Preparing services...
2022-11-22T14:36:50.207316Z ERROR risingwave_meta::rpc::server: found error invalid hummock context 0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidContext(0)', src/meta/src/rpc/server.rs:574:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1791:5
  3: core::result::Result<T,E>::unwrap
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1113:23
   4: risingwave_meta::rpc::server::rpc_serve_with_store::{{closure}}
             at ./src/meta/src/rpc/server.rs:567:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
   6: risingwave_meta::rpc::server::rpc_serve::{{closure}}
             at ./src/meta/src/rpc/server.rs:120:13
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
   8: risingwave_meta::start::{{closure}}
             at ./src/meta/src/lib.rs:227:9
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/future.rs:124:9
  11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  12: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/park/thread.rs:267:54
  13: tokio::coop::with_budget::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:102:9
  14: std::thread::local::LocalKey<T>::try_with
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:446:16
  15: std::thread::local::LocalKey<T>::with
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:422:9
  16: tokio::coop::with_budget
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:95:5
  17: tokio::coop::budget
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:72:5
  18: tokio::park::thread::CachedParkThread::block_on
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/park/thread.rs:267:31
  19: tokio::runtime::enter::Enter::block_on
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/enter.rs:152:13
  20: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/mod.rs:79:9
  21: tokio::runtime::Runtime::block_on
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/mod.rs:492:44
  22: risingwave_rt::main_okk
             at ./src/utils/runtime/src/lib.rs:264:5
  23: meta_node::main
             at ./src/cmd/src/bin/meta_node.rs:30:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Tue 22 Nov 2022 14:36:50 UTC [risedev]: Program exited with 134
```

### To Reproduce

- Checkout https://github.com/risingwavelabs/risingwave/pull/6466 , commit `114fda9791279c2585d83f1077cfd4803f6265ad`

```bash 
# tool not waiting on node to get ready 
risedev install

# start services from scratch with 3 meta nodes 
risedev k ; risedev clean-data ; risedev d 3etcd-3meta-1cn-1fe ; risedev l

# check logs. Delete node which is leader (look for "This node currently is a leader") 
risedev del <nam-of-leader>

# look for crashed meta node
risedev l 
```

### Expected behavior

- New leader should take over without problems

### Additional context

`we have no leader` is an error. The cluster has a leader.

**Comment by zwang28** [comment] 2022-11-22 16:08
The error is caused by hummock manager receiving a meta store transaction failure.
Hummock manager will write meta store during startup, where it checks the meta leader key:
https://github.com/risingwavelabs/risingwave/blob/10129f90c9832d964139d13933e2368f5544e455/src/meta/src/hummock/manager/mod.rs#L498

**Comment by CAJan93** [comment] 2022-11-23 11:10
Will likely implement a solution for this as a follow-up of https://github.com/risingwavelabs/risingwave/pull/6466

**Comment by CAJan93** [comment] 2022-12-07 10:20
Solution: We should not start the hummock manager in standby node. We can only start the hummock manager after becoming a leader node. Thank you for the suggestion @yezizp2012

**Comment by CAJan93** [comment] 2022-12-16 09:39
When we initialise the hummock manager only after the node became a leader, we will still get an error, however a slightly different one: (see [logs/stack trace](https://github.com/risingwavelabs/risingwave/files/10244557/meta-node-25690.log)) 

CC @yezizp2012

**Comment by yezizp2012** [comment] 2022-12-16 09:53
> When we initialise the hummock manager only after the node became a leader, we will still get an error, however a slightly different one: (see [logs/stack trace](https://github.com/risingwavelabs/risingwave/files/10244557/meta-node-25690.log))
> 
> CC @yezizp2012

This is still related to stored results generated by the selection in the meta store. Please **ENSURE** that the leader information in MetaSrvEnv is correctly updated when follower get elected. I guess this is the main cause. 😃

**Comment by yezizp2012** [comment] 2022-12-16 10:35
And this's just a bug under your development of HA in meta. Let's record it in one of the subtasks tracked in #6936 , maybe #6936 ? Since it's not a bug in the main branch and very misleading, I will close it.

**Closed by yezizp2012** 2022-12-16 10:35 UTC
Labels: type/bug
