### ISSUE TITLE
Meta node panic during nexmark q4 test execution

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#7961] opened 2023-02-16 05:17 UTC
### Describe the bug

The compute node and compactor nodes had restarted according to the pod metrics.

![image](https://user-images.githubusercontent.com/35356271/219274719-c1e348c8-fe45-4dfd-bb56-ad1379e2d196.png)

[buildkite pipeline job](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/397#0186559c-4eed-4ac9-996d-c3b0c6b00822)

[grafana](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&from=1676475088000&to=1676476442000&to=&var-namespace=nexmark-0-3-4-5-7-daily-20230215) 

The logs on CloudWatch are really weird. Can't paste all of them here.
[meta log](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fnexmark-0-3-4-5-7-daily-20230215/log-events/ip-10-0-70-43.ap-southeast-1.compute.internal-risingwave.var.log.containers.benchmark-risingwave-meta-0_nexmark-0-3-4-5-7-daily-20230215_meta-36b323a6c469bd75173fb6a4bf555221cb727407a36dc8825752b8bb702ff419.log)
[compute log](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fnexmark-0-3-4-5-7-daily-20230215/log-events/ip-10-0-84-122.ap-southeast-1.compute.internal-risingwave.var.log.containers.benchmark-risingwave-compute-0_nexmark-0-3-4-5-7-daily-20230215_compute-4be88b9fa4372bbe0bfe3dd5de222939a0e245d9cd384f772cfbe910b1e4a69e.log)

### Additional context

Slack: https://risingwave-labs.slack.com/archives/C0340PNL68P/p1676524176660369

**Comment by cyliu0** [comment] 2023-02-17 02:18
[This pipeline job](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/402#01865b30-cb83-4dd0-a214-acfa8f2e677b) also got compute node panic and compactor & meta node restarted during nexmark q102 execution.

[Grafana](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&from=1676571080000&to=1676572674000&to=&var-namespace=nexmark-101-102-103-104-105-daily-20230216)

[CloudWatch Logs](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fnexmark-101-102-103-104-105-daily-20230216$3FlogStreamNameFilter$3D)

**Comment by yezizp2012** [comment] 2023-02-17 04:37
> [This pipeline job](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/402#01865b30-cb83-4dd0-a214-acfa8f2e677b) also got compute node panic and compactor & meta node restarted during nexmark q102 execution.
> 
> [Grafana](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave-benchmark?orgId=1&from=1676571080000&to=1676572674000&to=&var-namespace=nexmark-101-102-103-104-105-daily-20230216)
> 
> [CloudWatch Logs](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Frisingwave$252Frls-apse1-eks-a$252Fnexmark-101-102-103-104-105-daily-20230216$3FlogStreamNameFilter$3D)

Same issue as described in slack, the root cause is that meta node exited without any logs, probably due to connection problem with etcd. 
1. meta supports `advertise_addr` configuration, other nodes discovering new meta's issue will be fixed.
2. need more investigation on meta's exit, avoid exits due to network jitter between meta and etcd. @shanicky 's working on it.

**Closed** 2023-03-22 09:10 UTC
Labels: type/bug
