### ISSUE TITLE
feat: checkpoint commit callback (for cdc-connector)

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15464] opened 2024-03-05 09:42 UTC
### Some background go first

Our cdc connector consumes PG cdc events while acking to the PG server at regular intervals the offset (lsn) that has been consumed. Then upstream PG will assume that wal log of those offsets can be discarded.
https://github.com/risingwavelabs/risingwave/blob/e6d8d88bcef5a388a0a7a0669d9418d25194f138/java/connector-node/risingwave-connector-service/src/main/java/com/risingwave/connector/source/core/DbzCdcEventConsumer.java#L189-L199

DebeziumEngine will commit those marked offsets to upstream:
https://github.com/debezium/debezium/blob/4ca2a67b0d302c611b89b1931728377cf232ab6c/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java#L435-L436

### Findings 
After some investigation, I think the reason for the "_Cannot seek to the last known offset_" error is that **we ack the offset to PG before the checkpoint commit**. So that when the cluster recovered from a committed checkpoint, the restored offset may already been discarded by upstream PG.

Currently our framework doesn't have a [checkpoint commit callback](https://github.com/apache/flink/blob/cf5bb80b5fd965928ff75d415dd93e0b12fa1b49/flink-core/src/main/java/org/apache/flink/api/common/state/CheckpointListener.java#L98) mechanism to notify the source executor. An intuitive idea is to let Meta make a broadcast RPCs to each CNs in the cluster. cc @hzxa21 

To confirm the findings, I increase the offset flush interval to 30mins which is much large than the time required for the test and rerun the chaos test (stresschaos only and w/o memtable spill: [599](https://buildkite.com/risingwave-test/chaos-mesh/builds/599), [603](https://buildkite.com/risingwave-test/chaos-mesh/builds/603) ), the results show that the "Cannot seek" error is gone and btw mv check is passed.

But! when I run chaos test with 3CNs ([601](https://buildkite.com/risingwave-test/chaos-mesh/builds/601)) , even the error is gone, the source table is still unsynced with PG, I have no idea of this one right now.

_Originally posted by @StrikeW in https://github.com/risingwavelabs/risingwave/issues/15141#issuecomment-1959605692_

**Comment by fuyufjh** [comment] 2024-03-08 08:30
Note down the discussion with @BugenZhao.

Today we realized the requirement not only works for source but also works for sink. For example, if we want to provide exactly-once delivery for sink, the implementation will be like

1. Prepare: `SinkExecutor` writes data and make sure the data is persisted in target system but invisible to readers. 
2. Commit: The checkpoint commit callback calls sink to finalize the write by making all previous writes visible.

Hope we can design a general framework for this requirement, rather than being specific 
to CDC connectors.

**Comment by StrikeW** [comment] 2024-03-08 08:37
I think we can generalize the sink coordinator framework for this feature.

**Comment by hzxa21** [comment] 2024-03-08 08:41
> Today we realized the requirement not only works for source but also works for sink. For example, if we want to provide exactly-once delivery for sink, the implementation will be like

I think we have already implemented a general framework (sink coordinator) for sink and we need to extend it to source. you can check with @wenym1 for the details.

**Comment by BugenZhao** [comment] 2024-03-28 08:59
> Currently our framework doesn't have a [checkpoint commit callback](https://github.com/apache/flink/blob/cf5bb80b5fd965928ff75d415dd93e0b12fa1b49/flink-core/src/main/java/org/apache/flink/api/common/state/CheckpointListener.java#L98) mechanism to notify the source executor.

Does `StateStore::try_wait_epoch` achieve similar functionality? Can we delay the acknowledgement until the `try_wait_epoch` call returns to resolve this issue?

**Comment by StrikeW** [comment] 2024-03-29 02:27
The problem is we need to ack the source offset to upstream database **after** checkpoint has been committed.

> I think we can generalize the sink coordinator framework for this feature.

I revisited the workflow of sink coordinator, which is independent of the barriers collection workflow (initiated by `BarrierManager`). The sink executors communicate with sink coordinator solely. If we want to generalize the sink coordinator framework, I think we need to integrate it into barrier collection first, which would introduce unnecessary work right now.

> Does `StateStore::try_wait_epoch` achieve similar functionality? Can we delay the acknowledgement until the `try_wait_epoch` call returns to resolve this issue?

This is a good idea. Right now there is a existing `WaitEpochCommit` RPC from Meta to CN, we can leverage this and hook into barrier collection workflow to notify `Source`. The workflow be like:
1. Meta send `WaitEpochCommit` to CN when a barrier completed
2. `BarrierManager` in the CN notify all source exec via a channel
3. `Source exec interact with the cdc connector to ack the offset to upstream.

**Comment by hzxa21** [comment] 2024-03-29 03:33
I think the workflow can be simplified without RPC:
1. Source writes offset to source state table
2. On seeing checkpoint barrier, source flush states and await on `try_wait_epoch` without blocking the stream.
3. On `try_wait_epoch` succeeds, source ack offset to upstream

Note that because upstream receives ack after checkpoint has finished, it is possible that upstream will send already consumed message to source. To ensure exactly once consumption, source needs to filter out duplicate messages sent by upstream on recovery.

**Comment by BugenZhao** [comment] 2024-04-01 03:02
> I think the workflow can be simplified without RPC:

This is exactly what I mean! There's one more thing to be note that the procedure should be done in a concurrent or asynchronous manner.

**Comment by StrikeW** [comment] 2024-04-08 03:16
The coding of PR https://github.com/risingwavelabs/risingwave/pull/16058 is done, but the call to `wait_epoch` on local state store cannot receive notification and the barrier also piles up. Call for review of the code.

**Closed** 2024-04-12 12:03 UTC
Labels: priority/high, needs-design

**Comment by tabVersion** [comment] 2024-05-13 19:29
Hi all, I am revisiting the issue for implementing a general ack mechanism in source, thanks @xxchan for mentioning this. 

My major questions are:
1) for a mq with ack, it has a timeout for the staging queue. If a message fails to ack within the timeout, it will go back to the deliver queue and be delivered again to the clients. Then we can get a message twice in some cases, for example, an mq's timeout is 30min and at that time rw is experiencing heavy load, and it takes 35min to finish one epoch. Then all data in the epoch will be delivered twice (fails to achieve exactly-once semantic, and makes future traffic heavier). Is it desired or we gonna trigger a rollback in advance proactively for the promise? 
2) unlike a cdc-spec one, a general framework gonna retains all messages' ack-id. Considering a 30min sliding time window, we may have to persist millions of records. Shall we introducing a log store for it?

> BTW, this situation is also true for persisted pulsar source with 0 retention.

@yuhao-su can you share more about the case? IIRC, a non-persistent pulsar topic cannot seek to spec position and I think it is expected.

**Comment by yuhao-su** [comment] 2024-05-14 01:26
> can you share more about the case? IIRC, a non-persistent pulsar topic cannot seek to spec position and I think it is expected.

Replied in the issue.
