### ISSUE TITLE
streaming: tolerate compute error by default

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4625] opened 2022-08-14 07:56 UTC
There are different kinds of runtime errors for a streaming job:
- compute errors:
  - `ExprError`: e.g., division by zero, overflow
  - Other executor logic errors: e.g., scalar subquery with more than one row in some places
- system errors: e.g., OOM, lose connection to meta/storage. 

Currently, we treat all errors in the same way: every `Err` in an executor will be propagated to the actor, and then causes a panic in the whole worker node. 

For system errors, panicing makes some sense. They are _temporary_ and could be handled by some fault tolerance/failover mechanism.

For compute errors, they will cause _permanent_ data corruption to a MV. Failover doesn't help in this situation. We have to have a policy to *explicitly* handle them. **They should not cause panic**.

## (Prefer) Tolerate compute error by default

A simple strategy is to fill a `NULL` whenever a compute error happens. At the same time, we need to collect and report the error (maybe by the actor (and also for #37)) and prompt the user. (Maybe we need something like a warning store)

### Rationale
- A streaming job is expected to be long-lived. In many cases, the user may not want to pause it when something goes wrong. We should try our best to _extend its life_.
- In practice, we can almost do nothing (cheap) for corrupted data. To really fix the error, the user might have to drop and recreate the MV and maybe even replay the source.

### Problems
- Batch and streaming will have slightly different behavior for compute errors.
- Corruputed data will have long-lasting affects in the system, but this seems inevitable and it's user's responsibility to decide whether to continue use it (if we already provide enough warnings).

## Alternative: strict mode
Compute errors are rejected, but will not cause panic. The MV will be suspended and removed from further checkpoints. It can still be used to *serve outdated data without corruption*. To really fix the error, the user might still need to drop and recreate the MV.

### Problems
- Since we have MV on MV, there will be _cascading_ MV suspension.

### Make it configurable
We can make `strict_mode` an option and let the user to decide which is the expected behavior. But it seems that strict mode has limited benefits over non strict mode, and has significantly different behavior, so to make implementation simpler maybe we just use `const STRICT_MODE: bool` to static dispatch, without allowing configuring `strict_mode` at runtime. 

---

## Tracking
- [x] https://github.com/singularity-data/risingwave/pull/4652
- [ ] report error to fe and promt the user

**Comment by fuyufjh** [comment] 2022-10-12 02:31
Can we close this?

**Comment by xxchan** [comment] 2022-10-12 10:36
"Report error to fe and promt the user" is not yet implemented. What's your idea about its urgency?

**Comment by fuyufjh** [comment] 2022-12-19 10:15
It seems to need some further design. + @TennyZhuang

**Comment by hzxa21** [comment] 2023-02-17 11:50
I actually prefer the `Alternative: strict mode` idea since it gives user a choice on how to handle non-internal errors caused by users/messages. We can have a system table to store the list of suspended MVs as well as the detail error messages.

**Comment by xxchan** [comment] 2023-02-17 12:20
IIRC it's because we thought MV suspension is unnecessary complexity..?

**Comment by xxchan** [comment] 2023-02-17 12:29
... Or we just decided to delay implementing it till actual needs occur 😇

**Comment by hzxa21** [comment] 2023-02-17 12:36
> IIRC it's because we thought MV suspension is unnecessary complexity..?

My hunch is that this is unvaoidable since we don't know what possible outcome can be when error happens, especially given that we have supported sinking to external system.

For example, if we only allow tolerating the error and skipping messages, it can cause incorrect results in batch query and undesired behaviors to the downstream sink, which may or may not be reverted and recovered. That is why I think providing a way to stop when error happens makes sense. Even though users cannot do much other than drop and re-create the MV when bad things happen, they can at least limit the radius of impact. (random thoughts - maybe in some cases users can resume without recreating the MV although these cases can be rare: for file source, user can fix the bad file and resume)

What the default behavior should be remains debatable.

**Comment by jon-chuang** [comment] 2023-02-28 10:35
> scalar subquery with more than one row in some places

Minor detail, but need your confirmation @xxchan : Currently, for stream jobs, a max one row property is ensured from the perspective of frontend. Hence, I don't think this example is relevant.

**Comment by xxchan** [comment] 2023-02-28 10:53
@jon-chuang  IIRC at the time of creating this issue,
- max1row is not handled yet. So if it's disabled now, this is not relevant any more.
- Besides that, we only came up with the expr (maybe also aggregation?) errors as compute errors (data-related).

**Comment by jon-chuang** [comment] 2023-02-28 11:05
Error tolerance mode hierarchy / granularity is proposed as follows:

- system (cluster): 
  - batch_compute (mode:relaxed unimplemented)
  - stream_compute (mode:relaxed default)
  - batch_source (mode:relaxed unimplemented)
  - stream_source (mode:relaxed default)
- stream job (per job - overrides system config):
  - stream_source (mode:relaxed default)
  - stream_compute (mode:relaxed default)
- ~~session:~~
  - ~~batch_compute (mode:relaxed unimplemented)~~
  - ~~batch_source (mode:relaxed unimplemented)~~

For stream job config, if the `mode` for upstream component is strict, then when it is suspended, the MV is suspended. Likewise, all downstream MVs to a suspended MV are suspended. So the model is a taint model. However, the `mode` only applies to whether a given MV/source is suspended if an error originates within it, or if it will NULL-pad the rows.

We can skip implementing a per-job config. Still not sure what should be the default for risingwave cloud.

**Closed** 2023-07-20 17:46 UTC
Labels: type/feature, component/streaming, user-facing-changes
